# Generated by Django 4.2.6 on 2023-12-05 19:34

from django.db import migrations

from ..services import update_defaults

class Migration(migrations.Migration):
    dependencies = [
        ("defaults", "0002_initial"),
    ]

    operations = []
