# Generated by Django 4.2.6 on 2023-11-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defaults", "0002_auto_20231104_2203"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="defaultmedhistory",
            name="defaults_defaultmedhistory_unique_user_sideeffect_default",
        ),
        migrations.AddConstraint(
            model_name="defaultmedhistory",
            constraint=models.UniqueConstraint(
                fields=("user", "contraindication", "medhistorytype", "treatment", "trttype"),
                name="defaults_defaultmedhistory_unique_user_default",
            ),
        ),
    ]
