# Generated by Django 4.2.6 on 2024-02-01 01:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("defaults", "0003_auto_20231205_1934"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="defaultflaretrtsettings",
            name="defaults_defaultflaretrtsettings_gouthelper_default",
        ),
    ]
