# Generated by Django 4.2.6 on 2024-07-29 17:06

from django.db import migrations

from ..services import update_defaults


class Migration(migrations.Migration):
    dependencies = [
        ("defaults", "0003_initial"),
    ]

    operations = [migrations.RunPython(update_defaults)]
