# Generated by Django 4.2.6 on 2024-02-01 01:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("defaults", "0004_remove_defaultflaretrtsettings_defaults_defaultflaretrtsettings_gouthelper_default"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="defaultppxtrtsettings",
            name="defaults_defaultppxtrtsettings_gouthelper_default",
        ),
        migrations.RemoveConstraint(
            model_name="defaultulttrtsettings",
            name="defaults_defaultulttrtsettings_gouthelper_default",
        ),
    ]
