# Generated by Django 5.1.3 on 2024-11-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defaults", "0004_auto_20240729_1706"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicaldefaulttrt",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical default trt",
                "verbose_name_plural": "historical default trts",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalflareaidsettings",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical flare aid settings",
                "verbose_name_plural": "historical flare aid settingss",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalppxaidsettings",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical ppx aid settings",
                "verbose_name_plural": "historical ppx aid settingss",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalultaidsettings",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical ult aid settings",
                "verbose_name_plural": "historical ult aid settingss",
            },
        ),
        migrations.AlterField(
            model_name="historicaldefaulttrt",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalflareaidsettings",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalppxaidsettings",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalultaidsettings",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
