# Generated by Django 4.2.6 on 2024-03-16 14:55

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ("defaults", "0006_flareaidsettings_historicalflareaidsettings_and_more"),
    ]

    operations = []
