# Generated by Django 4.2.6 on 2024-03-19 21:38

from django.db import migrations

from ..services import update_defaults


class Migration(migrations.Migration):
    dependencies = [
        ("defaults", "0008_remove_defaultmedhistory_defaults_defaultmedhistory_medhistorytype_valid_and_more"),
    ]

    operations = [migrations.RunPython(update_defaults)]
