# Generated by Django 4.2.6 on 2024-03-27 16:15

from django.db import migrations, models

def delete_old_default_medhistorytypes(apps, schema_editor):
    DefaultMedHistory = apps.get_model("defaults", "DefaultMedHistory")
    DefaultMedHistory.objects.filter(medhistorytype="ALLOPURINOLHYPERSENSITIVITY").delete()
    DefaultMedHistory.objects.filter(medhistorytype="FEBUXOSTATHYPERSENSITIVITY").delete()

class Migration(migrations.Migration):
    dependencies = [
        ("defaults", "0009_auto_20240319_2138"),
    ]

    operations = [
        migrations.RunPython(delete_old_default_medhistorytypes),
        migrations.RemoveConstraint(
            model_name="defaultmedhistory",
            name="defaults_defaultmedhistory_medhistorytype_valid",
        ),
        migrations.AlterField(
            model_name="defaultmedhistory",
            name="medhistorytype",
            field=models.CharField(
                choices=[
                    ("ANGINA", "Angina"),
                    ("ANTICOAGULATION", "Anticoagulation"),
                    ("BLEED", "Bleed"),
                    ("CAD", "Coronary Artery Disease"),
                    ("CHF", "Congestive Heart Failure"),
                    ("CKD", "Chronic Kidney Disease"),
                    ("COLCHICINEINTERACTION", "Colchicine Medication Interaction"),
                    ("DIABETES", "Diabetes"),
                    ("EROSIONS", "Erosions"),
                    ("GASTRICBYPASS", "Gastric Bypass"),
                    ("GOUT", "Gout"),
                    ("HEARTATTACK", "Heart Attack"),
                    ("HEPATITIS", "Hepatitis or Cirrhosis"),
                    ("HYPERTENSION", "Hypertension"),
                    ("HYPERURICEMIA", "Hyperuricemia"),
                    ("IBD", "Inflammatory Bowel Disease"),
                    ("MENOPAUSE", "Post-Menopausal"),
                    ("ORGANTRANSPLANT", "Organ Transplant"),
                    ("OSTEOPOROSIS", "Osteoporosis"),
                    ("PUD", "Peptic Ulcer Disease"),
                    ("PVD", "Peripheral Vascular Disease"),
                    ("STROKE", "Stroke"),
                    ("TOPHI", "Tophi"),
                    ("URATESTONES", "Urate kidney stones"),
                    ("XOIINTERACTION", "Xanthine Oxidase Inhibitor Medication Interaction"),
                ],
                max_length=30,
                verbose_name="History Type",
            ),
        ),
        migrations.AddConstraint(
            model_name="defaultmedhistory",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "medhistorytype__in",
                        [
                            "ANGINA",
                            "ANTICOAGULATION",
                            "BLEED",
                            "CAD",
                            "CHF",
                            "CKD",
                            "COLCHICINEINTERACTION",
                            "DIABETES",
                            "EROSIONS",
                            "GASTRICBYPASS",
                            "GOUT",
                            "HEARTATTACK",
                            "HEPATITIS",
                            "HYPERTENSION",
                            "HYPERURICEMIA",
                            "IBD",
                            "MENOPAUSE",
                            "ORGANTRANSPLANT",
                            "OSTEOPOROSIS",
                            "PUD",
                            "PVD",
                            "STROKE",
                            "TOPHI",
                            "URATESTONES",
                            "XOIINTERACTION",
                        ],
                    )
                ),
                name="defaults_defaultmedhistory_medhistorytype_valid",
            ),
        ),
    ]
