# Generated by Django 4.2.6 on 2024-03-27 16:15

from django.db import migrations

from ..services import update_defaults

class Migration(migrations.Migration):
    dependencies = [
        ("defaults", "0010_remove_defaultmedhistory_defaults_defaultmedhistory_medhistorytype_valid_and_more"),
    ]

    operations = [migrations.RunPython(update_defaults)]
