# Generated by Django 4.2.6 on 2024-03-29 12:22

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defaults", "0011_auto_20240327_1615"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalultaidsettings",
            name="dose_adj_interval",
            field=models.DurationField(
                default=datetime.timedelta(days=42),
                help_text="How often is the dose adjusted?",
                validators=[
                    django.core.validators.MaxValueValidator(datetime.timedelta(days=84)),
                    django.core.validators.MinValueValidator(datetime.timedelta(days=14)),
                ],
                verbose_name="Dose Adjustment Interval",
            ),
        ),
        migrations.AddField(
            model_name="ultaidsettings",
            name="dose_adj_interval",
            field=models.DurationField(
                default=datetime.timedelta(days=42),
                help_text="How often is the dose adjusted?",
                validators=[
                    django.core.validators.MaxValueValidator(datetime.timedelta(days=84)),
                    django.core.validators.MinValueValidator(datetime.timedelta(days=14)),
                ],
                verbose_name="Dose Adjustment Interval",
            ),
        ),
        migrations.AddConstraint(
            model_name="ultaidsettings",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("dose_adj_interval__lte", datetime.timedelta(days=84)),
                    ("dose_adj_interval__gte", datetime.timedelta(days=14)),
                ),
                name="defaults_ultaidsettings_dose_adj_interval_valid",
            ),
        ),
    ]
