# Generated by Django 4.2.6 on 2024-01-28 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("flareaids", "0005_remove_flareaid_medallergys_and_more"),
        ("ultaids", "0004_remove_ultaid_medallergys_remove_ultaid_medhistorys"),
        ("ppxaids", "0004_remove_ppxaid_medallergys_remove_ppxaid_medhistorys"),
        ("medallergys", "0003_historicalmedallergy_user_medallergy_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmedallergy",
            name="flareaid",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="flareaids.flareaid",
            ),
        ),
        migrations.AddField(
            model_name="historicalmedallergy",
            name="ppxaid",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ppxaids.ppxaid",
            ),
        ),
        migrations.AddField(
            model_name="historicalmedallergy",
            name="ultaid",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ultaids.ultaid",
            ),
        ),
        migrations.AddField(
            model_name="medallergy",
            name="flareaid",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s",
                to="flareaids.flareaid",
            ),
        ),
        migrations.AddField(
            model_name="medallergy",
            name="ppxaid",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s",
                to="ppxaids.ppxaid",
            ),
        ),
        migrations.AddField(
            model_name="medallergy",
            name="ultaid",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s",
                to="ultaids.ultaid",
            ),
        ),
        migrations.AddConstraint(
            model_name="medallergy",
            constraint=models.UniqueConstraint(
                fields=("flareaid", "treatment"), name="medallergys_medallergy_unique_flareaid"
            ),
        ),
        migrations.AddConstraint(
            model_name="medallergy",
            constraint=models.UniqueConstraint(
                fields=("ppxaid", "treatment"), name="medallergys_medallergy_unique_ppxaid"
            ),
        ),
        migrations.AddConstraint(
            model_name="medallergy",
            constraint=models.UniqueConstraint(
                fields=("ultaid", "treatment"), name="medallergys_medallergy_unique_ultaid"
            ),
        ),
    ]
