# Generated by Django 4.2.6 on 2024-01-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medallergys", "0004_historicalmedallergy_flareaid_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="medallergy",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("flareaid__isnull", True),
                        ("ppxaid__isnull", True),
                        ("ultaid__isnull", True),
                        ("user__isnull", False),
                    ),
                    ("user__isnull", True),
                    models.Q(
                        ("flareaid__isnull", True),
                        ("ppxaid__isnull", True),
                        ("ultaid__isnull", True),
                        ("user__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="medallergys_medallergy_user_aid_exclusive",
            ),
        ),
    ]
