# Generated by Django 4.2.6 on 2024-01-29 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ultaids", "0004_remove_ultaid_medallergys_remove_ultaid_medhistorys"),
        ("flareaids", "0005_remove_flareaid_medallergys_and_more"),
        ("ppxaids", "0004_remove_ppxaid_medallergys_remove_ppxaid_medhistorys"),
        ("medallergys", "0006_alter_medallergy_flareaid_alter_medallergy_ppxaid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medallergy",
            name="flareaid",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="flareaids.flareaid"
            ),
        ),
        migrations.AlterField(
            model_name="medallergy",
            name="ppxaid",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="ppxaids.ppxaid"
            ),
        ),
        migrations.AlterField(
            model_name="medallergy",
            name="ultaid",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="ultaids.ultaid"
            ),
        ),
    ]
