# Generated by Django 4.2.6 on 2024-01-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medallergys", "0007_alter_medallergy_flareaid_alter_medallergy_ppxaid_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="medallergy",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("ppxaid__isnull", False),
                        (
                            "treatment__in",
                            [
                                "CELECOXIB",
                                "COLCHICINE",
                                "DICLOFENAC",
                                "IBUPROFEN",
                                "INDOMETHACIN",
                                "METHYLPREDNISOLONE",
                                "MELOXICAM",
                                "NAPROXEN",
                                "PREDNISONE",
                            ],
                        ),
                    ),
                    ("ppxaid__isnull", True),
                    _connector="OR",
                ),
                name="medallergys_medallergy_ppxaid_treatment",
            ),
        ),
    ]
