# Generated by Django 4.2.6 on 2024-01-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medallergys", "0008_medallergy_medallergys_medallergy_ppxaid_treatment"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="medallergy",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("flareaid__isnull", False),
                        (
                            "treatment__in",
                            [
                                "CELECOXIB",
                                "COLCHICINE",
                                "DICLOFENAC",
                                "IBUPROFEN",
                                "INDOMETHACIN",
                                "METHYLPREDNISOLONE",
                                "MELOXICAM",
                                "NAPROXEN",
                                "PREDNISONE",
                            ],
                        ),
                    ),
                    ("flareaid__isnull", True),
                    _connector="OR",
                ),
                name="medallergys_medallergy_flareaid_treatment",
            ),
        ),
        migrations.AddConstraint(
            model_name="medallergy",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("treatment__in", ["ALLOPURINOL", "FEBUXOSTAT", "PROBENECID"]), ("ultaid__isnull", False)
                    ),
                    ("ultaid__isnull", True),
                    _connector="OR",
                ),
                name="medallergys_medallergy_ultaid_treatment",
            ),
        ),
    ]
