# Generated by Django 4.2.6 on 2024-03-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medallergys", "0009_medallergy_medallergys_medallergy_flareaid_treatment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmedallergy",
            name="matype",
            field=models.CharField(
                blank=True,
                choices=[("HYPERSENSITIVITY", "hypersensitivity"), ("OTHER", "other")],
                help_text="Type of medication allergy.",
                max_length=30,
                null=True,
                verbose_name="Medication Allergy Type",
            ),
        ),
        migrations.AddField(
            model_name="historicalmedallergy",
            name="other",
            field=models.CharField(
                blank=True,
                help_text="If the medication allergy is not in the list, enter it here.",
                max_length=75,
                null=True,
                verbose_name="Other Medication Allergy",
            ),
        ),
        migrations.AddField(
            model_name="medallergy",
            name="matype",
            field=models.CharField(
                blank=True,
                choices=[("HYPERSENSITIVITY", "hypersensitivity"), ("OTHER", "other")],
                help_text="Type of medication allergy.",
                max_length=30,
                null=True,
                verbose_name="Medication Allergy Type",
            ),
        ),
        migrations.AddField(
            model_name="medallergy",
            name="other",
            field=models.CharField(
                blank=True,
                help_text="If the medication allergy is not in the list, enter it here.",
                max_length=75,
                null=True,
                verbose_name="Other Medication Allergy",
            ),
        ),
        migrations.AddConstraint(
            model_name="medallergy",
            constraint=models.CheckConstraint(
                check=models.Q(("matype__in", ["HYPERSENSITIVITY", "OTHER"])),
                name="medallergys_medallergy_matype_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="medallergy",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("matype", "OTHER"), ("other__isnull", False)), ("other__isnull", True), _connector="OR"
                ),
                name="medallergys_medallergy_other_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="medallergy",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("treatment", "ALLOPURINOL"),
                        models.Q(("treatment", "FEBUXOSTAT"), ("matype__in", ["HYPERSENSITIVITY", "OTHER"])),
                        ("matype__isnull", True),
                        ("matype__isnull", True),
                        _connector="OR",
                    )
                ),
                name="medallergys_medallergy_xoi_valid",
            ),
        ),
    ]
