# Generated by Django 4.2.6 on 2024-07-29 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ppxs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("goalurates", "0002_initial"),
        ("ppxaids", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ppx",
            name="user",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalppx",
            name="goalurate",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="goalurates.goalurate",
            ),
        ),
        migrations.AddField(
            model_name="historicalppx",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalppx",
            name="ppxaid",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ppxaids.ppxaid",
            ),
        ),
        migrations.AddField(
            model_name="historicalppx",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="ppx",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("goalurate__isnull", True), ("ppxaid__isnull", True), ("user__isnull", False)),
                    ("user__isnull", True),
                    _connector="OR",
                ),
                name="ppxs_ppx_user_xor_ppxaid",
            ),
        ),
        migrations.AddConstraint(
            model_name="ppx",
            constraint=models.CheckConstraint(
                check=models.Q(("indication__gte", 0), ("indication__lte", 2)), name="ppxs_ppx_indication_gte_0_lte_2"
            ),
        ),
    ]
