# Generated by Django 4.2.6 on 2024-01-25 17:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ppxs", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalppx",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ppx",
            name="user",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="historicalppx",
            name="indication",
            field=models.IntegerField(
                choices=[(0, "Not Indicated"), (1, "Conditionally Indicated"), (2, "Indicated")],
                default=0,
                help_text="Does the patient have an indication for prophylaxis?",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)],
                verbose_name="Indication",
            ),
        ),
        migrations.AlterField(
            model_name="ppx",
            name="indication",
            field=models.IntegerField(
                choices=[(0, "Not Indicated"), (1, "Conditionally Indicated"), (2, "Indicated")],
                default=0,
                help_text="Does the patient have an indication for prophylaxis?",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)],
                verbose_name="Indication",
            ),
        ),
    ]
