# Generated by Django 5.1.3 on 2024-11-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ppxs", "0003_remove_ppx_ppxs_ppx_user_xor_ppxaid_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalppx",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical ppx",
                "verbose_name_plural": "historical ppxs",
            },
        ),
        migrations.AlterField(
            model_name="historicalppx",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
