# Generated by Django 4.2.6 on 2024-01-28 20:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ppxs", "0003_historicalppx_user_ppx_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ppx",
            name="labs",
        ),
        migrations.RemoveField(
            model_name="ppx",
            name="medhistorys",
        ),
    ]
