# Generated by Django 4.2.6 on 2024-04-16 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ppxaids", "0004_remove_ppxaid_medallergys_remove_ppxaid_medhistorys"),
        ("ppxs", "0004_remove_ppx_labs_remove_ppx_medhistorys"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalppx",
            name="ppxaid",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ppxaids.ppxaid",
            ),
        ),
        migrations.AddField(
            model_name="ppx",
            name="ppxaid",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="ppxaids.ppxaid"
            ),
        ),
        migrations.AlterField(
            model_name="historicalppx",
            name="starting_ult",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")],
                default=False,
                help_text="Is the patient starting ULT?",
                verbose_name="Starting Urate-Lowering Therapy (ULT)",
            ),
        ),
        migrations.AlterField(
            model_name="ppx",
            name="starting_ult",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")],
                default=False,
                help_text="Is the patient starting ULT?",
                verbose_name="Starting Urate-Lowering Therapy (ULT)",
            ),
        ),
        migrations.AddConstraint(
            model_name="ppx",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("ppxaid__isnull", True), ("user__isnull", False)),
                    ("user__isnull", True),
                    _connector="OR",
                ),
                name="ppxs_ppx_user_xor_ppxaid",
            ),
        ),
        migrations.AddConstraint(
            model_name="ppx",
            constraint=models.CheckConstraint(
                check=models.Q(("indication__gte", 0), ("indication__lte", 2)), name="ppxs_ppx_indication_gte_0_lte_2"
            ),
        ),
    ]
