# Generated by Django 4.2.6 on 2024-04-22 22:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ppxs", "0005_historicalppx_ppxaid_ppx_ppxaid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalppx",
            name="starting_ult",
        ),
        migrations.RemoveField(
            model_name="ppx",
            name="starting_ult",
        ),
    ]
