# Generated by Django 4.2.6 on 2024-04-29 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("goalurates", "0004_remove_goalurate_medhistorys"),
        ("ppxs", "0006_remove_historicalppx_starting_ult_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ppx",
            name="ppxs_ppx_user_xor_ppxaid",
        ),
        migrations.AddField(
            model_name="historicalppx",
            name="goalurate",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="goalurates.goalurate",
            ),
        ),
        migrations.AddField(
            model_name="ppx",
            name="goalurate",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="goalurates.goalurate"
            ),
        ),
        migrations.AddConstraint(
            model_name="ppx",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("goalurate__isnull", True), ("ppxaid__isnull", True), ("user__isnull", False)),
                    ("user__isnull", True),
                    _connector="OR",
                ),
                name="ppxs_ppx_user_xor_ppxaid",
            ),
        ),
    ]
