# Generated by Django 4.2.6 on 2024-07-29 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("flareaids", "0001_initial"),
        ("genders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalflareaid",
            name="gender",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="genders.gender",
            ),
        ),
    ]
