# Generated by Django 4.2.6 on 2023-12-05 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("medhistorys", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dateofbirths", "0002_initial"),
        ("genders", "0001_initial"),
        ("medallergys", "0001_initial"),
        ("flareaids", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalflareaid",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="flareaid",
            name="dateofbirth",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="dateofbirths.dateofbirth"),
        ),
        migrations.AddField(
            model_name="flareaid",
            name="gender",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="genders.gender"
            ),
        ),
        migrations.AddField(
            model_name="flareaid",
            name="medallergys",
            field=models.ManyToManyField(to="medallergys.medallergy"),
        ),
        migrations.AddField(
            model_name="flareaid",
            name="medhistorys",
            field=models.ManyToManyField(to="medhistorys.medhistory"),
        ),
    ]
