# Generated by Django 4.2.6 on 2024-01-28 20:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flareaids", "0004_flareaid_user_historicalflareaid_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flareaid",
            name="medallergys",
        ),
        migrations.RemoveField(
            model_name="flareaid",
            name="medhistorys",
        ),
    ]
