# Generated by Django 4.2.6 on 2023-11-04 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime
import django_extensions.db.fields
import rules.contrib.models
import simple_history.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalMedHistory",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                (
                    "medhistorytype",
                    models.CharField(
                        choices=[
                            ("ALLOPURINOLHYPERSENSITIVITY", "Allopurinol Hypersensitivity Syndrome"),
                            ("ANGINA", "Angina"),
                            ("ANTICOAGULATION", "Anticoagulation"),
                            ("BLEED", "Bleed"),
                            ("CAD", "Coronary Artery Disease"),
                            ("CHF", "Congestive Heart Failure"),
                            ("CKD", "Chronic Kidney Disease"),
                            ("COLCHICINEINTERACTION", "Colchicine Medication Interaction"),
                            ("DIABETES", "Diabetes"),
                            ("EROSIONS", "Erosions"),
                            ("FEBUXOSTATHYPERSENSITIVITY", "Febuxostat Hypersensitivity Syndrome"),
                            ("GASTRICBYPASS", "Gastric Bypass"),
                            ("GOUT", "Gout"),
                            ("HEARTATTACK", "Heart Attack"),
                            ("HYPERTENSION", "Hypertension"),
                            ("HYPERURICEMIA", "Hyperuricemia"),
                            ("IBD", "Inflammatory Bowel Disease"),
                            ("MENOPAUSE", "Post-Menopausal"),
                            ("ORGANTRANSPLANT", "Organ Transplant"),
                            ("OSTEOPOROSIS", "Osteoporosis"),
                            ("PVD", "Peripheral Vascular Disease"),
                            ("STROKE", "Stroke"),
                            ("TOPHI", "Tophi"),
                            ("URATESTONES", "Urate kidney stones"),
                            ("XOIINTERACTION", "Xanthine Oxidase Inhibitor Medication Interaction"),
                        ],
                        editable=False,
                        max_length=50,
                        verbose_name="MedHistory Type",
                    ),
                ),
                (
                    "set_date",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="What date this MedHistory was last created or modified?",
                        null=True,
                        verbose_name="Date MedHistory Created or Modified",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
            ],
            options={
                "verbose_name": "historical med history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="MedHistory",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "medhistorytype",
                    models.CharField(
                        choices=[
                            ("ALLOPURINOLHYPERSENSITIVITY", "Allopurinol Hypersensitivity Syndrome"),
                            ("ANGINA", "Angina"),
                            ("ANTICOAGULATION", "Anticoagulation"),
                            ("BLEED", "Bleed"),
                            ("CAD", "Coronary Artery Disease"),
                            ("CHF", "Congestive Heart Failure"),
                            ("CKD", "Chronic Kidney Disease"),
                            ("COLCHICINEINTERACTION", "Colchicine Medication Interaction"),
                            ("DIABETES", "Diabetes"),
                            ("EROSIONS", "Erosions"),
                            ("FEBUXOSTATHYPERSENSITIVITY", "Febuxostat Hypersensitivity Syndrome"),
                            ("GASTRICBYPASS", "Gastric Bypass"),
                            ("GOUT", "Gout"),
                            ("HEARTATTACK", "Heart Attack"),
                            ("HYPERTENSION", "Hypertension"),
                            ("HYPERURICEMIA", "Hyperuricemia"),
                            ("IBD", "Inflammatory Bowel Disease"),
                            ("MENOPAUSE", "Post-Menopausal"),
                            ("ORGANTRANSPLANT", "Organ Transplant"),
                            ("OSTEOPOROSIS", "Osteoporosis"),
                            ("PVD", "Peripheral Vascular Disease"),
                            ("STROKE", "Stroke"),
                            ("TOPHI", "Tophi"),
                            ("URATESTONES", "Urate kidney stones"),
                            ("XOIINTERACTION", "Xanthine Oxidase Inhibitor Medication Interaction"),
                        ],
                        editable=False,
                        max_length=50,
                        verbose_name="MedHistory Type",
                    ),
                ),
                (
                    "set_date",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="What date this MedHistory was last created or modified?",
                        null=True,
                        verbose_name="Date MedHistory Created or Modified",
                    ),
                ),
            ],
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name="medhistory",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("set_date__isnull", False), ("set_date__lte", django.db.models.functions.datetime.Now())
                    ),
                    ("set_date__isnull", True),
                    _connector="OR",
                ),
                name="medhistorys_medhistory_set_date_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="medhistory",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "medhistorytype__in",
                        [
                            "ALLOPURINOLHYPERSENSITIVITY",
                            "ANGINA",
                            "ANTICOAGULATION",
                            "BLEED",
                            "CAD",
                            "CHF",
                            "CKD",
                            "COLCHICINEINTERACTION",
                            "DIABETES",
                            "EROSIONS",
                            "FEBUXOSTATHYPERSENSITIVITY",
                            "GASTRICBYPASS",
                            "GOUT",
                            "HEARTATTACK",
                            "HYPERTENSION",
                            "HYPERURICEMIA",
                            "IBD",
                            "MENOPAUSE",
                            "ORGANTRANSPLANT",
                            "OSTEOPOROSIS",
                            "PVD",
                            "STROKE",
                            "TOPHI",
                            "URATESTONES",
                            "XOIINTERACTION",
                        ],
                    )
                ),
                name="medhistorys_medhistory_medhistorytype_valid",
            ),
        ),
        migrations.AddField(
            model_name="historicalmedhistory",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Allopurinolhypersensitivity",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("medhistorys.medhistory",),
        ),
        migrations.CreateModel(
            name="Angina",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("medhistorys.medhistory",),
        ),
        migrations.CreateModel(
            name="Anticoagulation",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("medhistorys.medhistory",),
        ),
        migrations.CreateModel(
            name="Bleed",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("medhistorys.medhistory",),
        ),
        migrations.CreateModel(
            name="Cad",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("medhistorys.medhistory",),
        ),
        migrations.CreateModel(
            name="Chf",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("medhistorys.medhistory",),
        ),
        migrations.CreateModel(
            name="Ckd",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("medhistorys.medhistory",),
        ),
        migrations.CreateModel(
            name="Colchicineinteraction",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("medhistorys.medhistory",),
        ),
        migrations.CreateModel(
            name="Diabetes",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("medhistorys.medhistory",),
        ),
        migrations.CreateModel(
            name="Erosions",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("medhistorys.medhistory",),
        ),
        migrations.CreateModel(
            name="Febuxostathypersensitivity",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("medhistorys.medhistory",),
        ),
        migrations.CreateModel(
            name="Gastricbypass",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("medhistorys.medhistory",),
        ),
        migrations.CreateModel(
            name="Gout",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("medhistorys.medhistory",),
        ),
        migrations.CreateModel(
            name="Heartattack",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("medhistorys.medhistory",),
        ),
        migrations.CreateModel(
            name="Hypertension",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("medhistorys.medhistory",),
        ),
        migrations.CreateModel(
            name="Hyperuricemia",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("medhistorys.medhistory",),
        ),
        migrations.CreateModel(
            name="Ibd",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("medhistorys.medhistory",),
        ),
        migrations.CreateModel(
            name="Menopause",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("medhistorys.medhistory",),
        ),
        migrations.CreateModel(
            name="Organtransplant",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("medhistorys.medhistory",),
        ),
        migrations.CreateModel(
            name="Osteoporosis",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("medhistorys.medhistory",),
        ),
        migrations.CreateModel(
            name="Pvd",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("medhistorys.medhistory",),
        ),
        migrations.CreateModel(
            name="Stroke",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("medhistorys.medhistory",),
        ),
        migrations.CreateModel(
            name="Tophi",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("medhistorys.medhistory",),
        ),
        migrations.CreateModel(
            name="Uratestones",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("medhistorys.medhistory",),
        ),
        migrations.CreateModel(
            name="Xoiinteraction",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("medhistorys.medhistory",),
        ),
    ]
