# Generated by Django 4.2.6 on 2024-07-29 15:15

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import rules.contrib.models
import simple_history.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("goalurates", "0001_initial"),
        ("flareaids", "0002_initial"),
        ("flares", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalMedHistory",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                (
                    "medhistorytype",
                    models.CharField(
                        choices=[
                            ("ANGINA", "Angina"),
                            ("ANTICOAGULATION", "Anticoagulation"),
                            ("BLEED", "Bleed"),
                            ("CAD", "Coronary Artery Disease"),
                            ("CHF", "Congestive Heart Failure"),
                            ("CKD", "Chronic Kidney Disease"),
                            ("COLCHICINEINTERACTION", "Colchicine Medication Interaction"),
                            ("DIABETES", "Diabetes"),
                            ("EROSIONS", "Erosions"),
                            ("GASTRICBYPASS", "Gastric Bypass"),
                            ("GOUT", "Gout"),
                            ("HEARTATTACK", "Heart Attack"),
                            ("HEPATITIS", "Hepatitis or Cirrhosis"),
                            ("HYPERTENSION", "Hypertension"),
                            ("HYPERURICEMIA", "Hyperuricemia"),
                            ("IBD", "Inflammatory Bowel Disease"),
                            ("MENOPAUSE", "Post-Menopausal"),
                            ("ORGANTRANSPLANT", "Organ Transplant"),
                            ("OSTEOPOROSIS", "Osteoporosis"),
                            ("PUD", "Peptic Ulcer Disease"),
                            ("PVD", "Peripheral Vascular Disease"),
                            ("STROKE", "Stroke"),
                            ("TOPHI", "Tophi"),
                            ("URATESTONES", "Urate kidney stones"),
                            ("XOIINTERACTION", "Xanthine Oxidase Inhibitor Medication Interaction"),
                        ],
                        editable=False,
                        max_length=50,
                        verbose_name="MedHistory Type",
                    ),
                ),
                (
                    "set_date",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="What date this MedHistory was last created or modified?",
                        null=True,
                        verbose_name="Date MedHistory Created or Modified",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
            ],
            options={
                "verbose_name": "historical med history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="MedHistory",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "medhistorytype",
                    models.CharField(
                        choices=[
                            ("ANGINA", "Angina"),
                            ("ANTICOAGULATION", "Anticoagulation"),
                            ("BLEED", "Bleed"),
                            ("CAD", "Coronary Artery Disease"),
                            ("CHF", "Congestive Heart Failure"),
                            ("CKD", "Chronic Kidney Disease"),
                            ("COLCHICINEINTERACTION", "Colchicine Medication Interaction"),
                            ("DIABETES", "Diabetes"),
                            ("EROSIONS", "Erosions"),
                            ("GASTRICBYPASS", "Gastric Bypass"),
                            ("GOUT", "Gout"),
                            ("HEARTATTACK", "Heart Attack"),
                            ("HEPATITIS", "Hepatitis or Cirrhosis"),
                            ("HYPERTENSION", "Hypertension"),
                            ("HYPERURICEMIA", "Hyperuricemia"),
                            ("IBD", "Inflammatory Bowel Disease"),
                            ("MENOPAUSE", "Post-Menopausal"),
                            ("ORGANTRANSPLANT", "Organ Transplant"),
                            ("OSTEOPOROSIS", "Osteoporosis"),
                            ("PUD", "Peptic Ulcer Disease"),
                            ("PVD", "Peripheral Vascular Disease"),
                            ("STROKE", "Stroke"),
                            ("TOPHI", "Tophi"),
                            ("URATESTONES", "Urate kidney stones"),
                            ("XOIINTERACTION", "Xanthine Oxidase Inhibitor Medication Interaction"),
                        ],
                        editable=False,
                        max_length=50,
                        verbose_name="MedHistory Type",
                    ),
                ),
                (
                    "set_date",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="What date this MedHistory was last created or modified?",
                        null=True,
                        verbose_name="Date MedHistory Created or Modified",
                    ),
                ),
                (
                    "flare",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="flares.flare"
                    ),
                ),
                (
                    "flareaid",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="flareaids.flareaid"
                    ),
                ),
                (
                    "goalurate",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="goalurates.goalurate"
                    ),
                ),
            ],
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
