# Generated by Django 5.1.3 on 2024-11-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medhistorys", "0004_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalmedhistory",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical med history",
                "verbose_name_plural": "historical med historys",
            },
        ),
        migrations.AlterField(
            model_name="historicalmedhistory",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
