# Generated by Django 4.2.6 on 2023-12-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medhistorys", "0004_alter_medhistory_user"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="medhistory",
            constraint=models.UniqueConstraint(
                fields=("user", "medhistorytype"), name="medhistorys_medhistory_unique_user"
            ),
        ),
    ]
