# Generated by Django 4.2.6 on 2024-01-28 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ults", "0004_remove_ult_medhistorys"),
        ("ppxs", "0004_remove_ppx_labs_remove_ppx_medhistorys"),
        ("ultaids", "0004_remove_ultaid_medallergys_remove_ultaid_medhistorys"),
        ("flares", "0008_alter_historicalflare_urate_alter_flare_urate_and_more"),
        ("ppxaids", "0004_remove_ppxaid_medallergys_remove_ppxaid_medhistorys"),
        ("goalurates", "0004_remove_goalurate_medhistorys"),
        ("flareaids", "0005_remove_flareaid_medallergys_and_more"),
        ("medhistorys", "0005_medhistory_medhistorys_medhistory_unique_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmedhistory",
            name="flare",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="flares.flare",
            ),
        ),
        migrations.AddField(
            model_name="historicalmedhistory",
            name="flareaid",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="flareaids.flareaid",
            ),
        ),
        migrations.AddField(
            model_name="historicalmedhistory",
            name="goalurate",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="goalurates.goalurate",
            ),
        ),
        migrations.AddField(
            model_name="historicalmedhistory",
            name="ppx",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ppxs.ppx",
            ),
        ),
        migrations.AddField(
            model_name="historicalmedhistory",
            name="ppxaid",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ppxaids.ppxaid",
            ),
        ),
        migrations.AddField(
            model_name="historicalmedhistory",
            name="ult",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ults.ult",
            ),
        ),
        migrations.AddField(
            model_name="historicalmedhistory",
            name="ultaid",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ultaids.ultaid",
            ),
        ),
        migrations.AddField(
            model_name="medhistory",
            name="flare",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s",
                to="flares.flare",
            ),
        ),
        migrations.AddField(
            model_name="medhistory",
            name="flareaid",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s",
                to="flareaids.flareaid",
            ),
        ),
        migrations.AddField(
            model_name="medhistory",
            name="goalurate",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s",
                to="goalurates.goalurate",
            ),
        ),
        migrations.AddField(
            model_name="medhistory",
            name="ppx",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s",
                to="ppxs.ppx",
            ),
        ),
        migrations.AddField(
            model_name="medhistory",
            name="ppxaid",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s",
                to="ppxaids.ppxaid",
            ),
        ),
        migrations.AddField(
            model_name="medhistory",
            name="ult",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s",
                to="ults.ult",
            ),
        ),
        migrations.AddField(
            model_name="medhistory",
            name="ultaid",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s",
                to="ultaids.ultaid",
            ),
        ),
        migrations.AddConstraint(
            model_name="medhistory",
            constraint=models.UniqueConstraint(
                fields=("flare", "medhistorytype"), name="medhistorys_medhistory_unique_flare"
            ),
        ),
        migrations.AddConstraint(
            model_name="medhistory",
            constraint=models.UniqueConstraint(
                fields=("flareaid", "medhistorytype"), name="medhistorys_medhistory_unique_flareaid"
            ),
        ),
        migrations.AddConstraint(
            model_name="medhistory",
            constraint=models.UniqueConstraint(
                fields=("goalurate", "medhistorytype"), name="medhistorys_medhistory_unique_goalurate"
            ),
        ),
        migrations.AddConstraint(
            model_name="medhistory",
            constraint=models.UniqueConstraint(
                fields=("ppxaid", "medhistorytype"), name="medhistorys_medhistory_unique_ppxaid"
            ),
        ),
        migrations.AddConstraint(
            model_name="medhistory",
            constraint=models.UniqueConstraint(
                fields=("ppx", "medhistorytype"), name="medhistorys_medhistory_unique_ppx"
            ),
        ),
        migrations.AddConstraint(
            model_name="medhistory",
            constraint=models.UniqueConstraint(
                fields=("ultaid", "medhistorytype"), name="medhistorys_medhistory_unique_ultaid"
            ),
        ),
        migrations.AddConstraint(
            model_name="medhistory",
            constraint=models.UniqueConstraint(
                fields=("ult", "medhistorytype"), name="medhistorys_medhistory_unique_ult"
            ),
        ),
    ]
