# Generated by Django 4.2.6 on 2024-01-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medhistorys", "0006_historicalmedhistory_flare_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="medhistory",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("flare__isnull", True),
                        ("flareaid__isnull", True),
                        ("goalurate__isnull", True),
                        ("ppx__isnull", True),
                        ("ppxaid__isnull", True),
                        ("ult__isnull", True),
                        ("ultaid__isnull", True),
                        ("user__isnull", False),
                    ),
                    ("user__isnull", True),
                    models.Q(
                        ("flare__isnull", True),
                        ("flareaid__isnull", True),
                        ("goalurate__isnull", True),
                        ("ppx__isnull", True),
                        ("ppxaid__isnull", True),
                        ("ult__isnull", True),
                        ("ultaid__isnull", True),
                        ("user__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="medhistorys_medhistory_user_aid_exclusive",
            ),
        ),
    ]
