# Generated by Django 4.2.6 on 2024-01-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medhistorys", "0009_alter_medhistory_flare_alter_medhistory_flareaid_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="medhistory",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("flare__isnull", False),
                        (
                            "medhistorytype__in",
                            [
                                "ANGINA",
                                "CAD",
                                "CHF",
                                "CKD",
                                "GOUT",
                                "HEARTATTACK",
                                "HYPERTENSION",
                                "MENOPAUSE",
                                "PVD",
                                "STROKE",
                            ],
                        ),
                    ),
                    ("flare__isnull", True),
                    _connector="OR",
                ),
                name="medhistorys_medhistory_flare_mhtype",
            ),
        ),
        migrations.AddConstraint(
            model_name="medhistory",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("flareaid__isnull", False),
                        (
                            "medhistorytype__in",
                            [
                                "ANGINA",
                                "ANTICOAGULATION",
                                "BLEED",
                                "CAD",
                                "CHF",
                                "CKD",
                                "COLCHICINEINTERACTION",
                                "DIABETES",
                                "GASTRICBYPASS",
                                "HEARTATTACK",
                                "HYPERTENSION",
                                "IBD",
                                "ORGANTRANSPLANT",
                                "PVD",
                                "STROKE",
                            ],
                        ),
                    ),
                    ("flareaid__isnull", True),
                    _connector="OR",
                ),
                name="medhistorys_medhistory_flareaid_mhtype",
            ),
        ),
        migrations.AddConstraint(
            model_name="medhistory",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("goalurate__isnull", False), ("medhistorytype__in", ["EROSIONS", "TOPHI"])),
                    ("goalurate__isnull", True),
                    _connector="OR",
                ),
                name="medhistorys_medhistory_goalurate_mhtype",
            ),
        ),
        migrations.AddConstraint(
            model_name="medhistory",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("medhistorytype__in", ["GOUT"]), ("ppx__isnull", False)),
                    ("ppx__isnull", True),
                    _connector="OR",
                ),
                name="medhistorys_medhistory_ppx_mhtype",
            ),
        ),
        migrations.AddConstraint(
            model_name="medhistory",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        (
                            "medhistorytype__in",
                            [
                                "ANGINA",
                                "ANTICOAGULATION",
                                "BLEED",
                                "CAD",
                                "CHF",
                                "CKD",
                                "COLCHICINEINTERACTION",
                                "DIABETES",
                                "GASTRICBYPASS",
                                "HEARTATTACK",
                                "HYPERTENSION",
                                "IBD",
                                "ORGANTRANSPLANT",
                                "PVD",
                                "STROKE",
                            ],
                        ),
                        ("ppxaid__isnull", False),
                    ),
                    ("ppxaid__isnull", True),
                    _connector="OR",
                ),
                name="medhistorys_medhistory_ppxaid_mhtype",
            ),
        ),
        migrations.AddConstraint(
            model_name="medhistory",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("medhistorytype__in", ["CKD", "EROSIONS", "HYPERURICEMIA", "TOPHI", "URATESTONES"]),
                        ("ult__isnull", False),
                    ),
                    ("ult__isnull", True),
                    _connector="OR",
                ),
                name="medhistorys_medhistory_ult_mhtype",
            ),
        ),
        migrations.AddConstraint(
            model_name="medhistory",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        (
                            "medhistorytype__in",
                            [
                                "ALLOPURINOLHYPERSENSITIVITY",
                                "ANGINA",
                                "CAD",
                                "CHF",
                                "CKD",
                                "FEBUXOSTATHYPERSENSITIVITY",
                                "HEARTATTACK",
                                "ORGANTRANSPLANT",
                                "PVD",
                                "STROKE",
                                "XOIINTERACTION",
                            ],
                        ),
                        ("ultaid__isnull", False),
                    ),
                    ("ultaid__isnull", True),
                    _connector="OR",
                ),
                name="medhistorys_medhistory_ultaid_mhtype",
            ),
        ),
    ]
