# Generated by Django 4.2.6 on 2024-03-27 16:15

from django.db import migrations, models


def delete_old_medhistorytypes(apps, schema_editor):
    MedHistory = apps.get_model("medhistorys", "MedHistory")
    MedHistory.objects.filter(medhistorytype="ALLOPURINOLHYPERSENSITIVITY").delete()
    MedHistory.objects.filter(medhistorytype="FEBUXOSTATHYPERSENSITIVITY").delete()
    try:
        MedHistory.history.filter(medhistorytype="ALLOPURINOLHYPERSENSITIVITY").delete()
        MedHistory.history.filter(medhistorytype="FEBUXOSTATHYPERSENSITIVITY").delete()
    except AttributeError:
        pass

class Migration(migrations.Migration):
    dependencies = [
        ("medhistorys", "0011_pud_and_more"),
    ]

    operations = [
        migrations.RunPython(delete_old_medhistorytypes),
        migrations.DeleteModel(
            name="Allopurinolhypersensitivity",
        ),
        migrations.DeleteModel(
            name="Febuxostathypersensitivity",
        ),
        migrations.CreateModel(
            name="Hepatitis",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("medhistorys.medhistory",),
        ),
        migrations.RemoveConstraint(
            model_name="medhistory",
            name="medhistorys_medhistory_ultaid_mhtype",
        ),
        migrations.RemoveConstraint(
            model_name="medhistory",
            name="medhistorys_medhistory_medhistorytype_valid",
        ),
        migrations.AlterField(
            model_name="historicalmedhistory",
            name="medhistorytype",
            field=models.CharField(
                choices=[
                    ("ANGINA", "Angina"),
                    ("ANTICOAGULATION", "Anticoagulation"),
                    ("BLEED", "Bleed"),
                    ("CAD", "Coronary Artery Disease"),
                    ("CHF", "Congestive Heart Failure"),
                    ("CKD", "Chronic Kidney Disease"),
                    ("COLCHICINEINTERACTION", "Colchicine Medication Interaction"),
                    ("DIABETES", "Diabetes"),
                    ("EROSIONS", "Erosions"),
                    ("GASTRICBYPASS", "Gastric Bypass"),
                    ("GOUT", "Gout"),
                    ("HEARTATTACK", "Heart Attack"),
                    ("HEPATITIS", "Hepatitis or Cirrhosis"),
                    ("HYPERTENSION", "Hypertension"),
                    ("HYPERURICEMIA", "Hyperuricemia"),
                    ("IBD", "Inflammatory Bowel Disease"),
                    ("MENOPAUSE", "Post-Menopausal"),
                    ("ORGANTRANSPLANT", "Organ Transplant"),
                    ("OSTEOPOROSIS", "Osteoporosis"),
                    ("PUD", "Peptic Ulcer Disease"),
                    ("PVD", "Peripheral Vascular Disease"),
                    ("STROKE", "Stroke"),
                    ("TOPHI", "Tophi"),
                    ("URATESTONES", "Urate kidney stones"),
                    ("XOIINTERACTION", "Xanthine Oxidase Inhibitor Medication Interaction"),
                ],
                editable=False,
                max_length=50,
                verbose_name="MedHistory Type",
            ),
        ),
        migrations.AlterField(
            model_name="medhistory",
            name="medhistorytype",
            field=models.CharField(
                choices=[
                    ("ANGINA", "Angina"),
                    ("ANTICOAGULATION", "Anticoagulation"),
                    ("BLEED", "Bleed"),
                    ("CAD", "Coronary Artery Disease"),
                    ("CHF", "Congestive Heart Failure"),
                    ("CKD", "Chronic Kidney Disease"),
                    ("COLCHICINEINTERACTION", "Colchicine Medication Interaction"),
                    ("DIABETES", "Diabetes"),
                    ("EROSIONS", "Erosions"),
                    ("GASTRICBYPASS", "Gastric Bypass"),
                    ("GOUT", "Gout"),
                    ("HEARTATTACK", "Heart Attack"),
                    ("HEPATITIS", "Hepatitis or Cirrhosis"),
                    ("HYPERTENSION", "Hypertension"),
                    ("HYPERURICEMIA", "Hyperuricemia"),
                    ("IBD", "Inflammatory Bowel Disease"),
                    ("MENOPAUSE", "Post-Menopausal"),
                    ("ORGANTRANSPLANT", "Organ Transplant"),
                    ("OSTEOPOROSIS", "Osteoporosis"),
                    ("PUD", "Peptic Ulcer Disease"),
                    ("PVD", "Peripheral Vascular Disease"),
                    ("STROKE", "Stroke"),
                    ("TOPHI", "Tophi"),
                    ("URATESTONES", "Urate kidney stones"),
                    ("XOIINTERACTION", "Xanthine Oxidase Inhibitor Medication Interaction"),
                ],
                editable=False,
                max_length=50,
                verbose_name="MedHistory Type",
            ),
        ),
        migrations.AddConstraint(
            model_name="medhistory",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "medhistorytype__in",
                        [
                            "ANGINA",
                            "ANTICOAGULATION",
                            "BLEED",
                            "CAD",
                            "CHF",
                            "CKD",
                            "COLCHICINEINTERACTION",
                            "DIABETES",
                            "EROSIONS",
                            "GASTRICBYPASS",
                            "GOUT",
                            "HEARTATTACK",
                            "HEPATITIS",
                            "HYPERTENSION",
                            "HYPERURICEMIA",
                            "IBD",
                            "MENOPAUSE",
                            "ORGANTRANSPLANT",
                            "OSTEOPOROSIS",
                            "PUD",
                            "PVD",
                            "STROKE",
                            "TOPHI",
                            "URATESTONES",
                            "XOIINTERACTION",
                        ],
                    )
                ),
                name="medhistorys_medhistory_medhistorytype_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="medhistory",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        (
                            "medhistorytype__in",
                            [
                                "ANGINA",
                                "CAD",
                                "CHF",
                                "CKD",
                                "HEARTATTACK",
                                "HEPATITIS",
                                "ORGANTRANSPLANT",
                                "PVD",
                                "STROKE",
                                "URATESTONES",
                                "XOIINTERACTION",
                            ],
                        ),
                        ("ultaid__isnull", False),
                    ),
                    ("ultaid__isnull", True),
                    _connector="OR",
                ),
                name="medhistorys_medhistory_ultaid_mhtype",
            ),
        ),
    ]
