# Generated by Django 4.2.6 on 2023-12-05 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("genders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalgender",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="gender",
            constraint=models.CheckConstraint(
                check=models.Q(("value__in", [0, 1])), name="genders_gender_value_check"
            ),
        ),
    ]
