# Generated by Django 5.1.3 on 2024-11-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genders", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalgender",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical gender",
                "verbose_name_plural": "historical genders",
            },
        ),
        migrations.AlterField(
            model_name="historicalgender",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
