# Generated by Django 4.2.6 on 2023-12-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genders", "0003_gender_user_historicalgender_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gender",
            name="value",
            field=models.IntegerField(
                choices=[(0, "Male"), (1, "Female")], help_text="Biological Sex", verbose_name="Gender"
            ),
        ),
        migrations.AlterField(
            model_name="historicalgender",
            name="value",
            field=models.IntegerField(
                choices=[(0, "Male"), (1, "Female")], help_text="Biological Sex", verbose_name="Gender"
            ),
        ),
    ]
