# Generated by Django 4.2.6 on 2023-12-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genders", "0004_alter_gender_value_alter_historicalgender_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gender",
            name="value",
            field=models.IntegerField(
                choices=[(0, "Male"), (1, "Female")],
                help_text='What is the patient\'s biological sex? <a href="/genders/about/" target="_next">Why do we need to know?</a>',
                verbose_name="Biological Sex",
            ),
        ),
        migrations.AlterField(
            model_name="historicalgender",
            name="value",
            field=models.IntegerField(
                choices=[(0, "Male"), (1, "Female")],
                help_text='What is the patient\'s biological sex? <a href="/genders/about/" target="_next">Why do we need to know?</a>',
                verbose_name="Biological Sex",
            ),
        ),
    ]
