# Generated by Django 4.2.6 on 2023-12-05 19:33

from django.db import migrations, models
import django_extensions.db.fields
import gouthelper.utils.fields
import markdownfield.models
import rules.contrib.models
import simple_history.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FLARE", "Flare"),
                            ("FLAREAID", "FlareAid"),
                            ("GOALURATE", "GoalUrate"),
                            ("LAB", "Lab"),
                            ("PPX", "Ppx"),
                            ("PPXAID", "PpxAid"),
                            ("TREATMENT", "Treatment"),
                            ("ULT", "Ult"),
                            ("ULTAID", "UltAid"),
                        ],
                        editable=False,
                        max_length=255,
                        null=True,
                        verbose_name="Context",
                    ),
                ),
                ("slug", models.SlugField(max_length=255)),
                (
                    "tag",
                    models.CharField(
                        blank=True,
                        choices=[("explanation", "Explanation"), ("warning", "Warning")],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("text", gouthelper.utils.fields.GouthelperMarkdownField(rendered_field="text_rendered")),
                ("text_rendered", markdownfield.models.RenderedMarkdownField()),
            ],
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContent",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                (
                    "context",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FLARE", "Flare"),
                            ("FLAREAID", "FlareAid"),
                            ("GOALURATE", "GoalUrate"),
                            ("LAB", "Lab"),
                            ("PPX", "Ppx"),
                            ("PPXAID", "PpxAid"),
                            ("TREATMENT", "Treatment"),
                            ("ULT", "Ult"),
                            ("ULTAID", "UltAid"),
                        ],
                        editable=False,
                        max_length=255,
                        null=True,
                        verbose_name="Context",
                    ),
                ),
                ("slug", models.SlugField(max_length=255)),
                (
                    "tag",
                    models.CharField(
                        blank=True,
                        choices=[("explanation", "Explanation"), ("warning", "Warning")],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("text", gouthelper.utils.fields.GouthelperMarkdownField(rendered_field="text_rendered")),
                ("text_rendered", markdownfield.models.RenderedMarkdownField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
            ],
            options={
                "verbose_name": "historical content",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
