# Generated by Django 4.2.6 on 2023-12-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contents", "0002_auto_20231104_2206"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="content",
            name="contents_content_valid_context",
        ),
        migrations.AlterField(
            model_name="content",
            name="context",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FLARE", "Flare"),
                    ("FLAREAID", "FlareAid"),
                    ("GOALURATE", "GoalUrate"),
                    ("LAB", "Lab"),
                    ("PPX", "Ppx"),
                    ("PPXAID", "PpxAid"),
                    ("TREATMENT", "Treatment"),
                    ("ULT", "Ult"),
                    ("ULTAID", "UltAid"),
                ],
                editable=False,
                max_length=255,
                null=True,
                verbose_name="Context",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontent",
            name="context",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FLARE", "Flare"),
                    ("FLAREAID", "FlareAid"),
                    ("GOALURATE", "GoalUrate"),
                    ("LAB", "Lab"),
                    ("PPX", "Ppx"),
                    ("PPXAID", "PpxAid"),
                    ("TREATMENT", "Treatment"),
                    ("ULT", "Ult"),
                    ("ULTAID", "UltAid"),
                ],
                editable=False,
                max_length=255,
                null=True,
                verbose_name="Context",
            ),
        ),
        migrations.AddConstraint(
            model_name="content",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "context__in",
                        ["FLARE", "FLAREAID", "GOALURATE", "LAB", "PPX", "PPXAID", "TREATMENT", "ULT", "ULTAID"],
                    )
                ),
                name="contents_content_valid_context",
            ),
        ),
    ]
