# Generated by Django 4.2.6 on 2023-12-05 19:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contents", "0002_initial"),
    ]

    operations = []
