# Generated by Django 4.2.6 on 2024-07-29 17:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contents", "0002_initial"),
    ]

    operations = []
