# Generated by Django 5.1.3 on 2024-11-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contents", "0003_auto_20240729_1706"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalcontent",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical content",
                "verbose_name_plural": "historical contents",
            },
        ),
        migrations.AlterField(
            model_name="historicalcontent",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
