# Generated by Django 4.2.6 on 2024-01-23 13:55

from django.db import migrations

from ..services import create_or_update_contents


class Migration(migrations.Migration):
    dependencies = [
        ("contents", "0004_remove_content_contents_content_valid_context_and_more"),
    ]

    operations = [migrations.RunPython(create_or_update_contents)]
