# Generated by Django 4.2.6 on 2024-03-19 21:50

from django.db import migrations

from ..services import create_or_update_contents

class Migration(migrations.Migration):
    dependencies = [
        ("contents", "0005_auto_20240123_1355"),
    ]

    operations = [migrations.RunPython(create_or_update_contents)]
