# Generated by Django 4.2.6 on 2023-12-05 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ults", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalult",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="ult",
            constraint=models.CheckConstraint(
                check=models.Q(("num_flares__in", [0, 1, 2])), name="ults_ult_num_flares_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="ult",
            constraint=models.CheckConstraint(
                check=models.Q(("freq_flares__in", [1, 2])), name="ults_ult_freq_flares_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="ult",
            constraint=models.CheckConstraint(
                check=models.Q(("indication__in", [0, 1, 2])), name="ults_ult_indication_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="ult",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("num_flares", 2), ("freq_flares__isnull", False)),
                    models.Q(("num_flares", 1), ("freq_flares__isnull", True)),
                    models.Q(("num_flares", 0), ("freq_flares__isnull", True)),
                    _connector="OR",
                ),
                name="ults_ult_freq_num_flares_valid",
            ),
        ),
    ]
