# Generated by Django 4.2.6 on 2024-07-29 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ultaids", "0002_initial"),
        ("ults", "0001_initial"),
        ("genders", "0002_initial"),
        ("dateofbirths", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ult",
            name="user",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalult",
            name="dateofbirth",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="dateofbirths.dateofbirth",
            ),
        ),
        migrations.AddField(
            model_name="historicalult",
            name="gender",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="genders.gender",
            ),
        ),
        migrations.AddField(
            model_name="historicalult",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalult",
            name="ultaid",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ultaids.ultaid",
            ),
        ),
        migrations.AddField(
            model_name="historicalult",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="ult",
            constraint=models.CheckConstraint(
                check=models.Q(("num_flares__in", [0, 1, 2])), name="ults_ult_num_flares_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="ult",
            constraint=models.CheckConstraint(
                check=models.Q(("freq_flares__in", [1, 2])), name="ults_ult_freq_flares_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="ult",
            constraint=models.CheckConstraint(
                check=models.Q(("indication__in", [0, 1, 2])), name="ults_ult_indication_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="ult",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("num_flares", 2), ("freq_flares__isnull", False)),
                    models.Q(("num_flares", 1), ("freq_flares__isnull", True)),
                    models.Q(("num_flares", 0), ("freq_flares__isnull", True)),
                    _connector="OR",
                ),
                name="ults_ult_freq_num_flares_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="ult",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("dateofbirth__isnull", True),
                        ("gender__isnull", True),
                        ("ultaid__isnull", True),
                        ("user__isnull", False),
                    ),
                    ("user__isnull", True),
                    _connector="OR",
                ),
                name="ults_ult_valid",
            ),
        ),
    ]
