# Generated by Django 4.2.6 on 2024-01-28 20:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ults", "0003_historicalult_user_ult_user_ult_ults_ult_valid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ult",
            name="medhistorys",
        ),
    ]
