# Generated by Django 4.2.6 on 2024-05-10 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ultaids", "0005_alter_ultaid_ethnicity"),
        ("ults", "0004_remove_ult_medhistorys"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ult",
            name="ults_ult_valid",
        ),
        migrations.AddField(
            model_name="historicalult",
            name="ultaid",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ultaids.ultaid",
            ),
        ),
        migrations.AddField(
            model_name="ult",
            name="ultaid",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="ultaids.ultaid"
            ),
        ),
        migrations.AddConstraint(
            model_name="ult",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("dateofbirth__isnull", True),
                        ("gender__isnull", True),
                        ("ultaid__isnull", True),
                        ("user__isnull", False),
                    ),
                    ("user__isnull", True),
                    _connector="OR",
                ),
                name="ults_ult_valid",
            ),
        ),
    ]
