# Generated by Django 4.2.6 on 2024-07-29 15:15

from django.db import migrations, models
import django_extensions.db.fields
import rules.contrib.models
import simple_history.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CkdDetail",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "dialysis",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")],
                        default=False,
                        help_text="Is the patient on <a href='https://en.wikipedia.org/wiki/Hemodialysis' target='_blank'>dialysis</a>?",
                        verbose_name="Dialysis",
                    ),
                ),
                (
                    "dialysis_duration",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "---------"),
                            ("LESSTHANSIX", "Less than six months"),
                            ("LESSTHANYEAR", "Between six months and a year"),
                            ("MORETHANYEAR", "More than a year"),
                        ],
                        default=None,
                        help_text="How long since the patient started dialysis?",
                        max_length=40,
                        null=True,
                        verbose_name="Time on Dialysis",
                    ),
                ),
                (
                    "dialysis_type",
                    models.CharField(
                        blank=True,
                        choices=[("HEMODIALYSIS", "Hemodialysis"), ("PERITONEAL", "Peritoneal")],
                        default=None,
                        help_text="What type of dialysis?",
                        max_length=40,
                        null=True,
                        verbose_name="Dialysis Type",
                    ),
                ),
                (
                    "stage",
                    models.IntegerField(
                        choices=[(None, "----"), (1, "I"), (2, "II"), (3, "III"), (4, "IV"), (5, "V")],
                        help_text="What <a href='https://www.kidney.org/sites/default/files/01 -10-7278_HBG_Ckd_Stages_Flyer_GFR.gif' target='_blank'>stage</a> CKD??",
                        verbose_name="CKD Stage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="GoutDetail",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "at_goal",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Yes"), (False, "No")],
                        default=None,
                        help_text="Is the patient at goal uric acid level? Goal is typically < 6.0 mg/dL.",
                        null=True,
                    ),
                ),
                (
                    "at_goal_long_term",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")],
                        default=False,
                        help_text="Has the patient been at goal uric acid six months or longer? Goal is typically < 6.0 mg/dL.",
                    ),
                ),
                (
                    "flaring",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Yes"), (False, "No")],
                        default=None,
                        help_text="Any recent gout flares?",
                        null=True,
                    ),
                ),
                (
                    "on_ppx",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")],
                        default=False,
                        help_text="Is the patient on flare prophylaxis therapy?",
                        verbose_name="On PPx?",
                    ),
                ),
                (
                    "on_ult",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")],
                        default=False,
                        help_text="Is the patient on or starting ULT (urate-lowering therapy)?",
                        verbose_name="On ULT?",
                    ),
                ),
                (
                    "starting_ult",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")],
                        default=False,
                        help_text="Is the patient starting ULT or is he or she still in the initial dose adjustment (titration) phase?",
                        verbose_name="Starting Urate-Lowering Therapy (ULT)",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCkdDetail",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                (
                    "dialysis",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")],
                        default=False,
                        help_text="Is the patient on <a href='https://en.wikipedia.org/wiki/Hemodialysis' target='_blank'>dialysis</a>?",
                        verbose_name="Dialysis",
                    ),
                ),
                (
                    "dialysis_duration",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "---------"),
                            ("LESSTHANSIX", "Less than six months"),
                            ("LESSTHANYEAR", "Between six months and a year"),
                            ("MORETHANYEAR", "More than a year"),
                        ],
                        default=None,
                        help_text="How long since the patient started dialysis?",
                        max_length=40,
                        null=True,
                        verbose_name="Time on Dialysis",
                    ),
                ),
                (
                    "dialysis_type",
                    models.CharField(
                        blank=True,
                        choices=[("HEMODIALYSIS", "Hemodialysis"), ("PERITONEAL", "Peritoneal")],
                        default=None,
                        help_text="What type of dialysis?",
                        max_length=40,
                        null=True,
                        verbose_name="Dialysis Type",
                    ),
                ),
                (
                    "stage",
                    models.IntegerField(
                        choices=[(None, "----"), (1, "I"), (2, "II"), (3, "III"), (4, "IV"), (5, "V")],
                        help_text="What <a href='https://www.kidney.org/sites/default/files/01 -10-7278_HBG_Ckd_Stages_Flyer_GFR.gif' target='_blank'>stage</a> CKD??",
                        verbose_name="CKD Stage",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
            ],
            options={
                "verbose_name": "historical ckd detail",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalGoutDetail",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                (
                    "at_goal",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Yes"), (False, "No")],
                        default=None,
                        help_text="Is the patient at goal uric acid level? Goal is typically < 6.0 mg/dL.",
                        null=True,
                    ),
                ),
                (
                    "at_goal_long_term",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")],
                        default=False,
                        help_text="Has the patient been at goal uric acid six months or longer? Goal is typically < 6.0 mg/dL.",
                    ),
                ),
                (
                    "flaring",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Yes"), (False, "No")],
                        default=None,
                        help_text="Any recent gout flares?",
                        null=True,
                    ),
                ),
                (
                    "on_ppx",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")],
                        default=False,
                        help_text="Is the patient on flare prophylaxis therapy?",
                        verbose_name="On PPx?",
                    ),
                ),
                (
                    "on_ult",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")],
                        default=False,
                        help_text="Is the patient on or starting ULT (urate-lowering therapy)?",
                        verbose_name="On ULT?",
                    ),
                ),
                (
                    "starting_ult",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")],
                        default=False,
                        help_text="Is the patient starting ULT or is he or she still in the initial dose adjustment (titration) phase?",
                        verbose_name="Starting Urate-Lowering Therapy (ULT)",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
            ],
            options={
                "verbose_name": "historical gout detail",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
