# Generated by Django 4.2.6 on 2024-04-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medhistorydetails", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goutdetail",
            name="hyperuricemic",
        ),
        migrations.RemoveField(
            model_name="historicalgoutdetail",
            name="hyperuricemic",
        ),
        migrations.AddField(
            model_name="goutdetail",
            name="at_goal",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Yes"), (False, "No")],
                default=None,
                help_text="Is the patient at goal uric acid level? Goal is typically < 6.0 mg/dL.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="goutdetail",
            name="at_goal_long_term",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")],
                default=False,
                help_text="Has the patient been at goal uric acid six months or longer? Goal is typically < 6.0 mg/dL.",
            ),
        ),
        migrations.AddField(
            model_name="goutdetail",
            name="starting_ult",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")],
                default=False,
                help_text="Is the patient starting ULT?",
                verbose_name="Starting Urate-Lowering Therapy (ULT)",
            ),
        ),
        migrations.AddField(
            model_name="historicalgoutdetail",
            name="at_goal",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Yes"), (False, "No")],
                default=None,
                help_text="Is the patient at goal uric acid level? Goal is typically < 6.0 mg/dL.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalgoutdetail",
            name="at_goal_long_term",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")],
                default=False,
                help_text="Has the patient been at goal uric acid six months or longer? Goal is typically < 6.0 mg/dL.",
            ),
        ),
        migrations.AddField(
            model_name="historicalgoutdetail",
            name="starting_ult",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")],
                default=False,
                help_text="Is the patient starting ULT?",
                verbose_name="Starting Urate-Lowering Therapy (ULT)",
            ),
        ),
        migrations.AlterField(
            model_name="goutdetail",
            name="flaring",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Yes"), (False, "No")],
                default=None,
                help_text="Any recent gout flares?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalgoutdetail",
            name="flaring",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Yes"), (False, "No")],
                default=None,
                help_text="Any recent gout flares?",
                null=True,
            ),
        ),
    ]
