# Generated by Django 5.1.3 on 2024-11-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medhistorydetails", "0003_alter_ckddetail_stage_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalckddetail",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical ckd detail",
                "verbose_name_plural": "historical ckd details",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalgoutdetail",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical gout detail",
                "verbose_name_plural": "historical gout details",
            },
        ),
        migrations.AlterField(
            model_name="historicalckddetail",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalgoutdetail",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
