# Generated by Django 4.2.6 on 2024-04-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medhistorydetails", "0003_remove_goutdetail_hyperuricemic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goutdetail",
            name="on_ult",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")],
                default=False,
                help_text="Is the patient on or starting ULT (urate-lowering therapy)?",
                verbose_name="On ULT?",
            ),
        ),
        migrations.AlterField(
            model_name="goutdetail",
            name="starting_ult",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")],
                default=False,
                help_text="Is the patient starting ULT or is he or she still in the initial dose adjustment (titration) phase?",
                verbose_name="Starting Urate-Lowering Therapy (ULT)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalgoutdetail",
            name="on_ult",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")],
                default=False,
                help_text="Is the patient on or starting ULT (urate-lowering therapy)?",
                verbose_name="On ULT?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalgoutdetail",
            name="starting_ult",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")],
                default=False,
                help_text="Is the patient starting ULT or is he or she still in the initial dose adjustment (titration) phase?",
                verbose_name="Starting Urate-Lowering Therapy (ULT)",
            ),
        ),
        migrations.AddConstraint(
            model_name="goutdetail",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("at_goal", False), ("at_goal_long_term", False)),
                    ("at_goal", True),
                    models.Q(("at_goal__isnull", True), ("at_goal_long_term", False)),
                    _connector="OR",
                ),
                name="medhistorydetails_goutdetail_at_goal_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="goutdetail",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("on_ult", False), ("starting_ult", False)), ("on_ult", True), _connector="OR"
                ),
                name="medhistorydetails_goutdetail_ult_valid",
            ),
        ),
    ]
