# Generated by Django 4.2.6 on 2024-04-28 18:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medhistorydetails", "0004_alter_goutdetail_on_ult_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="goutdetail",
            name="medhistorydetails_goutdetail_ult_valid",
        ),
    ]
