# Generated by Django 4.2.6 on 2024-05-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medhistorydetails", "0005_remove_goutdetail_medhistorydetails_goutdetail_ult_valid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ckddetail",
            name="stage",
            field=models.IntegerField(
                choices=[(None, "----"), (1, "I"), (2, "II"), (3, "III"), (4, "IV"), (5, "V")],
                help_text="What <a href='https://www.kidney.org/sites/default/files/01 -10-7278_HBG_Ckd_Stages_Flyer_GFR.gif' target='_blank'>stage</a> CKD??",
                verbose_name="CKD Stage",
            ),
        ),
        migrations.AlterField(
            model_name="historicalckddetail",
            name="stage",
            field=models.IntegerField(
                choices=[(None, "----"), (1, "I"), (2, "II"), (3, "III"), (4, "IV"), (5, "V")],
                help_text="What <a href='https://www.kidney.org/sites/default/files/01 -10-7278_HBG_Ckd_Stages_Flyer_GFR.gif' target='_blank'>stage</a> CKD??",
                verbose_name="CKD Stage",
            ),
        ),
    ]
