# Generated by Django 4.2.6 on 2023-11-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ethnicitys", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ethnicity",
            name="ethnicitys_ethnicity_value_check",
        ),
        migrations.AddConstraint(
            model_name="ethnicity",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "value__in",
                        [
                            "African American",
                            "Caucasian American",
                            "East African",
                            "Han Chinese",
                            "Hispanic",
                            "Hmong",
                            "Korean",
                            "Native American",
                            "Other",
                            "Pacific Islander",
                            "Thai",
                        ],
                    )
                ),
                name="ethnicitys_ethnicity_value_valid",
            ),
        ),
    ]
