# Generated by Django 4.2.6 on 2024-07-29 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ethnicitys", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalethnicity",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalethnicity",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ethnicity",
            name="user",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="ethnicity",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "value__in",
                        [
                            "African American",
                            "Caucasian American",
                            "East African",
                            "Han Chinese",
                            "Hispanic",
                            "Hmong",
                            "Korean",
                            "Native American",
                            "Other",
                            "Pacific Islander",
                            "Thai",
                        ],
                    )
                ),
                name="ethnicitys_ethnicity_value_valid",
            ),
        ),
    ]
