# Generated by Django 4.2.6 on 2023-12-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ethnicitys", "0003_ethnicity_user_historicalethnicity_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ethnicity",
            name="value",
            field=models.CharField(
                choices=[
                    ("African American", "African American"),
                    ("Caucasian American", "Caucasian American"),
                    ("East African", "East African"),
                    ("Han Chinese", "Han Chinese"),
                    ("Hispanic", "Hispanic"),
                    ("Hmong", "Hmong"),
                    ("Korean", "Korean"),
                    ("Native American", "Native American"),
                    ("Other", "Other"),
                    ("Pacific Islander", "Pacific Islander"),
                    ("Thai", "Thai"),
                ],
                help_text='What is the patient\'s ethnicity or race? <a href="/ethnicitys/about/" target="_next">Why do we need to know?</a>',
                max_length=40,
                verbose_name="Race",
            ),
        ),
        migrations.AlterField(
            model_name="historicalethnicity",
            name="value",
            field=models.CharField(
                choices=[
                    ("African American", "African American"),
                    ("Caucasian American", "Caucasian American"),
                    ("East African", "East African"),
                    ("Han Chinese", "Han Chinese"),
                    ("Hispanic", "Hispanic"),
                    ("Hmong", "Hmong"),
                    ("Korean", "Korean"),
                    ("Native American", "Native American"),
                    ("Other", "Other"),
                    ("Pacific Islander", "Pacific Islander"),
                    ("Thai", "Thai"),
                ],
                help_text='What is the patient\'s ethnicity or race? <a href="/ethnicitys/about/" target="_next">Why do we need to know?</a>',
                max_length=40,
                verbose_name="Race",
            ),
        ),
    ]
