# Generated by Django 5.1.3 on 2024-11-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicaladminprofile",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical admin profile",
                "verbose_name_plural": "historical admin profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpatientprofile",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical patient profile",
                "verbose_name_plural": "historical patient profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalproviderprofile",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical provider profile",
                "verbose_name_plural": "historical provider profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpseudopatientprofile",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical pseudopatient profile",
                "verbose_name_plural": "historical pseudopatient profiles",
            },
        ),
        migrations.AlterField(
            model_name="historicaladminprofile",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalpatientprofile",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalproviderprofile",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalpseudopatientprofile",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
