# Generated by Django 4.2.6 on 2024-07-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0005_alter_patientprofile_provider_pseudopatientprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpseudopatientprofile",
            name="provider_alias",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pseudopatientprofile",
            name="provider_alias",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name="pseudopatientprofile",
            constraint=models.UniqueConstraint(fields=("provider", "provider_alias"), name="unique_provider_alias"),
        ),
        migrations.AddConstraint(
            model_name="pseudopatientprofile",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("provider__isnull", False), ("provider_alias__isnull", False)),
                    models.Q(("provider__isnull", True), ("provider_alias__isnull", True)),
                    _connector="OR",
                ),
                name="has_alias_if_has_provider",
            ),
        ),
    ]
