# Generated by Django 4.2.6 on 2023-11-04 22:03

from django.db import migrations  # type: ignore

from ..services import update_defaults


class Migration(migrations.Migration):
    dependencies = [
        ("defaults", "0001_initial"),
    ]

    operations = [migrations.RunPython(update_defaults)]
