# Generated by Django 4.2.6 on 2023-11-04 20:11

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import rules.contrib.models
import simple_history.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ultaids", "0001_initial"),
        ("medhistorys", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalGoalUrate",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                (
                    "goal_urate",
                    models.DecimalField(
                        choices=[(Decimal("6"), "6.0 mg/dL"), (Decimal("5"), "5.0 mg/dL")],
                        decimal_places=1,
                        default=Decimal("6"),
                        help_text="What is the goal uric acid?",
                        max_digits=2,
                        verbose_name="Goal Uric Acid",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ultaid",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ultaids.ultaid",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical goal urate",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="GoalUrate",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "goal_urate",
                    models.DecimalField(
                        choices=[(Decimal("6"), "6.0 mg/dL"), (Decimal("5"), "5.0 mg/dL")],
                        decimal_places=1,
                        default=Decimal("6"),
                        help_text="What is the goal uric acid?",
                        max_digits=2,
                        verbose_name="Goal Uric Acid",
                    ),
                ),
                ("medhistorys", models.ManyToManyField(to="medhistorys.medhistory")),
                (
                    "ultaid",
                    models.OneToOneField(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="ultaids.ultaid"
                    ),
                ),
            ],
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name="goalurate",
            constraint=models.CheckConstraint(
                check=models.Q(("goal_urate__in", [Decimal("6"), Decimal("5")])),
                name="goalurates_goalurate_goal_urate_valid",
            ),
        ),
    ]
