# Generated by Django 4.2.6 on 2024-07-29 15:15

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ultaids", "0001_initial"),
        ("goalurates", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalgoalurate",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalgoalurate",
            name="ultaid",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ultaids.ultaid",
            ),
        ),
        migrations.AddField(
            model_name="historicalgoalurate",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="goalurate",
            name="ultaid",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="ultaids.ultaid"
            ),
        ),
        migrations.AddField(
            model_name="goalurate",
            name="user",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="goalurate",
            constraint=models.CheckConstraint(
                check=models.Q(("goal_urate__in", [Decimal("6"), Decimal("5")])),
                name="goalurates_goalurate_goal_urate_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="goalurate",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("ultaid__isnull", True), ("user__isnull", False)),
                    ("user__isnull", True),
                    _connector="OR",
                ),
                name="goalurates_goalurate_valid",
            ),
        ),
    ]
