# Generated by Django 4.2.6 on 2024-08-07 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ppxs", "0003_remove_ppx_ppxs_ppx_user_xor_ppxaid_and_more"),
        ("goalurates", "0002_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="goalurate",
            name="goalurates_goalurate_valid",
        ),
        migrations.AddField(
            model_name="goalurate",
            name="ppx",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="ppxs.ppx"
            ),
        ),
        migrations.AddField(
            model_name="historicalgoalurate",
            name="ppx",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ppxs.ppx",
            ),
        ),
        migrations.AddConstraint(
            model_name="goalurate",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("ppx__isnull", True), ("ultaid__isnull", True), ("user__isnull", False)),
                    ("user__isnull", True),
                    _connector="OR",
                ),
                name="goalurates_goalurate_valid",
            ),
        ),
    ]
