# Generated by Django 4.2.6 on 2024-01-18 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("goalurates", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goalurate",
            name="user",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalgoalurate",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="goalurate",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("ultaid__isnull", True), ("user__isnull", False)),
                    ("user__isnull", True),
                    _connector="OR",
                ),
                name="goalurates_goalurate_valid",
            ),
        ),
    ]
