# Generated by Django 4.2.6 on 2024-01-28 20:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goalurates", "0003_goalurate_user_historicalgoalurate_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goalurate",
            name="medhistorys",
        ),
    ]
