# Generated by Django 5.1.3 on 2024-11-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goalurates", "0003_remove_goalurate_goalurates_goalurate_valid_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalgoalurate",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical goal urate",
                "verbose_name_plural": "historical goal urates",
            },
        ),
        migrations.AlterField(
            model_name="historicalgoalurate",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
