# Generated by Django 4.2.6 on 2024-07-29 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ppxaids", "0001_initial"),
        ("dateofbirths", "0002_initial"),
        ("genders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ppxaid",
            name="user",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalppxaid",
            name="dateofbirth",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="dateofbirths.dateofbirth",
            ),
        ),
        migrations.AddField(
            model_name="historicalppxaid",
            name="gender",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="genders.gender",
            ),
        ),
        migrations.AddField(
            model_name="historicalppxaid",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalppxaid",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="ppxaid",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("dateofbirth__isnull", True), ("gender__isnull", True), ("user__isnull", False)),
                    models.Q(("dateofbirth__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="ppxaids_ppxaid_valid",
            ),
        ),
    ]
