# Generated by Django 4.2.6 on 2024-01-28 20:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ppxaids", "0003_historicalppxaid_user_ppxaid_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ppxaid",
            name="medallergys",
        ),
        migrations.RemoveField(
            model_name="ppxaid",
            name="medhistorys",
        ),
    ]
