# Generated by Django 4.2.6 on 2024-07-29 15:15

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields
import gouthelper.utils.models
import rules.contrib.models
import simple_history.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaselineCreatinine",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("lower_limit", models.DecimalField(decimal_places=2, default=Decimal("0.74"), max_digits=4)),
                (
                    "units",
                    models.CharField(
                        choices=[("MGDL", "mg/dL (milligrams per deciliter)")],
                        default="MGDL",
                        max_length=10,
                        verbose_name="Units",
                    ),
                ),
                ("upper_limit", models.DecimalField(decimal_places=2, default=Decimal("1.35"), max_digits=4)),
                ("value", models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Creatinine",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("lower_limit", models.DecimalField(decimal_places=2, default=Decimal("0.74"), max_digits=4)),
                (
                    "units",
                    models.CharField(
                        choices=[("MGDL", "mg/dL (milligrams per deciliter)")],
                        default="MGDL",
                        max_length=10,
                        verbose_name="Units",
                    ),
                ),
                ("upper_limit", models.DecimalField(decimal_places=2, default=Decimal("1.35"), max_digits=4)),
                ("value", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "date_drawn",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, help_text="What day was this lab drawn?"
                    ),
                ),
            ],
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalBaselineCreatinine",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("lower_limit", models.DecimalField(decimal_places=2, default=Decimal("0.74"), max_digits=4)),
                (
                    "units",
                    models.CharField(
                        choices=[("MGDL", "mg/dL (milligrams per deciliter)")],
                        default="MGDL",
                        max_length=10,
                        verbose_name="Units",
                    ),
                ),
                ("upper_limit", models.DecimalField(decimal_places=2, default=Decimal("1.35"), max_digits=4)),
                ("value", models.DecimalField(decimal_places=2, max_digits=4)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
            ],
            options={
                "verbose_name": "historical baseline creatinine",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCreatinine",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("lower_limit", models.DecimalField(decimal_places=2, default=Decimal("0.74"), max_digits=4)),
                (
                    "units",
                    models.CharField(
                        choices=[("MGDL", "mg/dL (milligrams per deciliter)")],
                        default="MGDL",
                        max_length=10,
                        verbose_name="Units",
                    ),
                ),
                ("upper_limit", models.DecimalField(decimal_places=2, default=Decimal("1.35"), max_digits=4)),
                ("value", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "date_drawn",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, help_text="What day was this lab drawn?"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
            ],
            options={
                "verbose_name": "historical creatinine",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalHlab5801",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                (
                    "date_drawn",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, help_text="What day was the HLA-B*5801 drawn?"
                    ),
                ),
                (
                    "value",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")],
                        help_text="HLA-B*5801 genotype present?",
                        verbose_name="HLA-B*5801",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
            ],
            options={
                "verbose_name": "historical hlab5801",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalUrate",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                (
                    "date_drawn",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, help_text="What day was this lab drawn?"
                    ),
                ),
                ("lower_limit", models.DecimalField(decimal_places=1, default=Decimal("3.5"), max_digits=3)),
                (
                    "units",
                    models.CharField(
                        choices=[("MGDL", "mg/dL (milligrams per deciliter)")],
                        default="MGDL",
                        max_length=10,
                        verbose_name="Units",
                    ),
                ),
                ("upper_limit", models.DecimalField(decimal_places=1, default=Decimal("7.2"), max_digits=3)),
                ("value", models.DecimalField(decimal_places=1, max_digits=3)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
            ],
            options={
                "verbose_name": "historical urate",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Hlab5801",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "date_drawn",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, help_text="What day was the HLA-B*5801 drawn?"
                    ),
                ),
                (
                    "value",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")],
                        help_text="HLA-B*5801 genotype present?",
                        verbose_name="HLA-B*5801",
                    ),
                ),
            ],
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Urate",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "date_drawn",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, help_text="What day was this lab drawn?"
                    ),
                ),
                ("lower_limit", models.DecimalField(decimal_places=1, default=Decimal("3.5"), max_digits=3)),
                (
                    "units",
                    models.CharField(
                        choices=[("MGDL", "mg/dL (milligrams per deciliter)")],
                        default="MGDL",
                        max_length=10,
                        verbose_name="Units",
                    ),
                ),
                ("upper_limit", models.DecimalField(decimal_places=1, default=Decimal("7.2"), max_digits=3)),
                ("value", models.DecimalField(decimal_places=1, max_digits=3)),
            ],
            options={
                "abstract": False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model, gouthelper.utils.models.GoalUrateMixin),
        ),
    ]
