# Generated by Django 4.2.6 on 2023-12-05 19:33

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("medhistorys", "0001_initial"),
        ("labs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalurate",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicallab",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalhlab5801",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalbaselinecreatinine",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalbaselinecreatinine",
            name="medhistory",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="medhistorys.medhistory",
            ),
        ),
        migrations.AddField(
            model_name="baselinecreatinine",
            name="medhistory",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="medhistorys.medhistory"),
        ),
        migrations.CreateModel(
            name="Urate",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("labs.lab",),
        ),
        migrations.AddConstraint(
            model_name="baselinecreatinine",
            constraint=models.CheckConstraint(
                check=models.Q(("labtype__in", ["CREATININE", "URATE"])), name="labs_baselinecreatinine_labtype_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="baselinecreatinine",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("labtype", "CREATININE"),
                        ("lower_limit", Decimal("0.74")),
                        ("units", "MGDL"),
                        ("upper_limit", Decimal("1.35")),
                    ),
                    models.Q(
                        ("labtype", "URATE"),
                        ("lower_limit", Decimal("3.5")),
                        ("units", "MGDL"),
                        ("upper_limit", Decimal("7.2")),
                        ("value__lte", Decimal("30.00")),
                    ),
                    _connector="OR",
                ),
                name="labs_baselinecreatinine_units_upper_lower_limits_valid",
            ),
        ),
    ]
