# Generated by Django 4.2.6 on 2024-07-29 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ppxs", "0001_initial"),
        ("labs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="urate",
            name="ppx",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="ppxs.ppx"),
        ),
    ]
