# Generated by Django 4.2.6 on 2023-11-18 15:56

from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):
    dependencies = [
        ("labs", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="hlab5801",
            constraint=models.CheckConstraint(
                check=models.Q(("date_drawn__lte", django.db.models.functions.datetime.Now())),
                name="labs_hlab5801_date_drawn_not_in_future",
            ),
        ),
    ]
