# Generated by Django 4.2.6 on 2024-07-29 15:15

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ppxs", "0001_initial"),
        ("akis", "0002_initial"),
        ("medhistorys", "0003_initial"),
        ("labs", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="urate",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="hlab5801",
            name="user",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalurate",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalurate",
            name="ppx",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ppxs.ppx",
            ),
        ),
        migrations.AddField(
            model_name="historicalurate",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalhlab5801",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalhlab5801",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalcreatinine",
            name="aki",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="akis.aki",
            ),
        ),
        migrations.AddField(
            model_name="historicalcreatinine",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalcreatinine",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalbaselinecreatinine",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalbaselinecreatinine",
            name="medhistory",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="medhistorys.medhistory",
            ),
        ),
        migrations.AddField(
            model_name="creatinine",
            name="aki",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="akis.aki"),
        ),
        migrations.AddField(
            model_name="creatinine",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="baselinecreatinine",
            name="medhistory",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="medhistorys.medhistory"),
        ),
        migrations.AddConstraint(
            model_name="urate",
            constraint=models.CheckConstraint(
                check=models.Q(("date_drawn__lte", django.db.models.functions.datetime.Now())),
                name="labs_urate_date_drawn_not_in_future",
            ),
        ),
        migrations.AddConstraint(
            model_name="urate",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("ppx__isnull", True), ("user__isnull", False)),
                    models.Q(("ppx__isnull", False), ("user__isnull", True)),
                    models.Q(("ppx__isnull", True), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="labs_urate_user_ppx_exclusive",
            ),
        ),
        migrations.AddConstraint(
            model_name="urate",
            constraint=models.CheckConstraint(
                check=models.Q(("lower_limit", Decimal("3.5")), ("units", "MGDL"), ("upper_limit", Decimal("7.2"))),
                name="labs_urate_units_upper_lower_limits_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="hlab5801",
            constraint=models.CheckConstraint(
                check=models.Q(("date_drawn__lte", django.db.models.functions.datetime.Now())),
                name="labs_hlab5801_date_drawn_not_in_future",
            ),
        ),
        migrations.AddConstraint(
            model_name="creatinine",
            constraint=models.CheckConstraint(
                check=models.Q(("lower_limit", Decimal("0.74")), ("units", "MGDL"), ("upper_limit", Decimal("1.35"))),
                name="labs_creatinine_units_upper_lower_limits_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="baselinecreatinine",
            constraint=models.CheckConstraint(
                check=models.Q(("lower_limit", Decimal("0.74")), ("units", "MGDL"), ("upper_limit", Decimal("1.35"))),
                name="labs_baselinecreatinine_units_upper_lower_limits_valid",
            ),
        ),
    ]
