# Generated by Django 5.1.3 on 2024-11-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labs", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalbaselinecreatinine",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical baseline creatinine",
                "verbose_name_plural": "historical baseline creatinines",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcreatinine",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical creatinine",
                "verbose_name_plural": "historical creatinines",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalhlab5801",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical hlab5801",
                "verbose_name_plural": "historical hlab5801s",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalurate",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical urate",
                "verbose_name_plural": "historical urates",
            },
        ),
        migrations.AlterField(
            model_name="historicalbaselinecreatinine",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalcreatinine",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalhlab5801",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalurate",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
