# Generated by Django 4.2.6 on 2024-01-28 20:18

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields
import rules.contrib.models
import simple_history.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("labs", "0006_historicalhlab5801_user_hlab5801_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalUrate",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                (
                    "date_drawn",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, help_text="What day was this lab drawn?"
                    ),
                ),
                ("lower_limit", models.DecimalField(decimal_places=1, default=Decimal("3.5"), max_digits=3)),
                (
                    "units",
                    models.CharField(
                        choices=[("MGDL", "mg/dL (milligrams per deciliter)")],
                        default="MGDL",
                        max_length=10,
                        verbose_name="Units",
                    ),
                ),
                ("upper_limit", models.DecimalField(decimal_places=1, default=Decimal("7.2"), max_digits=3)),
                ("value", models.DecimalField(decimal_places=1, max_digits=3)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
            ],
            options={
                "verbose_name": "historical urate",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name="historicallab",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicallab",
            name="user",
        ),
        migrations.RemoveField(
            model_name="lab",
            name="user",
        ),
        migrations.DeleteModel(
            name="Urate",
        ),
        migrations.RemoveConstraint(
            model_name="baselinecreatinine",
            name="labs_baselinecreatinine_labtype_valid",
        ),
        migrations.RemoveConstraint(
            model_name="baselinecreatinine",
            name="labs_baselinecreatinine_units_upper_lower_limits_valid",
        ),
        migrations.RemoveField(
            model_name="baselinecreatinine",
            name="labtype",
        ),
        migrations.RemoveField(
            model_name="historicalbaselinecreatinine",
            name="labtype",
        ),
        migrations.AlterField(
            model_name="baselinecreatinine",
            name="lower_limit",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.74"), max_digits=4),
        ),
        migrations.AlterField(
            model_name="baselinecreatinine",
            name="units",
            field=models.CharField(
                choices=[("MGDL", "mg/dL (milligrams per deciliter)")],
                default="MGDL",
                max_length=10,
                verbose_name="Units",
            ),
        ),
        migrations.AlterField(
            model_name="baselinecreatinine",
            name="upper_limit",
            field=models.DecimalField(decimal_places=2, default=Decimal("1.35"), max_digits=4),
        ),
        migrations.AlterField(
            model_name="baselinecreatinine",
            name="value",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name="historicalbaselinecreatinine",
            name="lower_limit",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.74"), max_digits=4),
        ),
        migrations.AlterField(
            model_name="historicalbaselinecreatinine",
            name="units",
            field=models.CharField(
                choices=[("MGDL", "mg/dL (milligrams per deciliter)")],
                default="MGDL",
                max_length=10,
                verbose_name="Units",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbaselinecreatinine",
            name="upper_limit",
            field=models.DecimalField(decimal_places=2, default=Decimal("1.35"), max_digits=4),
        ),
        migrations.AlterField(
            model_name="historicalbaselinecreatinine",
            name="value",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AddConstraint(
            model_name="baselinecreatinine",
            constraint=models.CheckConstraint(
                check=models.Q(("lower_limit", Decimal("0.74")), ("units", "MGDL"), ("upper_limit", Decimal("1.35"))),
                name="labs_baselinecreatinine_units_upper_lower_limits_valid",
            ),
        ),
        migrations.CreateModel(
            name="Urate",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "date_drawn",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, help_text="What day was this lab drawn?"
                    ),
                ),
                ("lower_limit", models.DecimalField(decimal_places=1, default=Decimal("3.5"), max_digits=3)),
                (
                    "units",
                    models.CharField(
                        choices=[("MGDL", "mg/dL (milligrams per deciliter)")],
                        default="MGDL",
                        max_length=10,
                        verbose_name="Units",
                    ),
                ),
                ("upper_limit", models.DecimalField(decimal_places=1, default=Decimal("7.2"), max_digits=3)),
                ("value", models.DecimalField(decimal_places=1, max_digits=3)),
            ],
            options={
                "abstract": False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.DeleteModel(
            name="HistoricalLab",
        ),
    ]
