# Generated by Django 4.2.6 on 2024-01-28 20:18

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("flares", "0008_alter_historicalflare_urate_alter_flare_urate_and_more"),
        ("ppxs", "0004_remove_ppx_labs_remove_ppx_medhistorys"),
        ("labs", "0007_historicalurate_remove_historicallab_history_user_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Lab",
        ),
        migrations.AddField(
            model_name="historicalurate",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalurate",
            name="ppx",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ppxs.ppx",
            ),
        ),
        migrations.AddField(
            model_name="historicalurate",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="urate",
            name="ppx",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="ppxs.ppx"),
        ),
        migrations.AddField(
            model_name="urate",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="urate",
            constraint=models.CheckConstraint(
                check=models.Q(("date_drawn__lte", django.db.models.functions.datetime.Now())),
                name="labs_urate_date_drawn_not_in_future",
            ),
        ),
        migrations.AddConstraint(
            model_name="urate",
            constraint=models.CheckConstraint(
                check=models.Q(("lower_limit", Decimal("3.5")), ("units", "MGDL"), ("upper_limit", Decimal("7.2"))),
                name="labs_urate_units_upper_lower_limits_valid",
            ),
        ),
    ]
