# Generated by Django 4.2.6 on 2024-01-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labs", "0008_delete_lab_historicalurate_history_user_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="urate",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("ppx__isnull", True), ("user__isnull", False)),
                    models.Q(("ppx__isnull", False), ("user__isnull", True)),
                    models.Q(("ppx__isnull", True), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="labs_urate_user_ppx_exclusive",
            ),
        ),
    ]
