# Generated by Django 4.2.6 on 2024-05-18 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("akis", "0004_aki_resolved_historicalaki_resolved"),
        ("labs", "0011_historicalcreatinine_creatinine_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creatinine",
            name="aki",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="akis.aki"
            ),
        ),
    ]
