# Generated by Django 4.2.6 on 2024-05-19 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("akis", "0005_alter_aki_user"),
        ("labs", "0012_alter_creatinine_aki"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creatinine",
            name="aki",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="akis.aki"),
        ),
    ]
