# Generated by Django 4.2.6 on 2023-12-05 19:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.datetime


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dateofbirths", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaldateofbirth",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="dateofbirth",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "value__lte",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.functions.datetime.Now(), "-", models.Value(datetime.timedelta(days=6570))
                        ),
                    )
                ),
                name="dateofbirth_18_years_or_older",
            ),
        ),
    ]
