# Generated by Django 4.2.6 on 2023-11-04 22:00

import datetime
from django.db import migrations, models
import django.db.models.expressions
import django.db.models.functions.datetime


class Migration(migrations.Migration):
    dependencies = [
        ("dateofbirths", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dateofbirth",
            name="dateofbirth_18_years_or_older",
        ),
        migrations.AddConstraint(
            model_name="dateofbirth",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "value__lte",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.functions.datetime.Now(), "-", models.Value(datetime.timedelta(days=6570))
                        ),
                    )
                ),
                name="dateofbirth_18_years_or_older",
            ),
        ),
    ]
