# Generated by Django 4.2.6 on 2024-07-29 15:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.datetime


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dateofbirths", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaldateofbirth",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicaldateofbirth",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dateofbirth",
            name="user",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="dateofbirth",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "value__lte",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.functions.datetime.Now(), "-", models.Value(datetime.timedelta(days=6570))
                        ),
                    )
                ),
                name="dateofbirth_18_years_or_older",
            ),
        ),
    ]
