# Generated by Django 4.2.6 on 2024-07-29 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ultaids", "0001_initial"),
        ("labs", "0003_initial"),
        ("ethnicitys", "0002_initial"),
        ("genders", "0002_initial"),
        ("dateofbirths", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ultaid",
            name="user",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalultaid",
            name="dateofbirth",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="dateofbirths.dateofbirth",
            ),
        ),
        migrations.AddField(
            model_name="historicalultaid",
            name="ethnicity",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ethnicitys.ethnicity",
            ),
        ),
        migrations.AddField(
            model_name="historicalultaid",
            name="gender",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="genders.gender",
            ),
        ),
        migrations.AddField(
            model_name="historicalultaid",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalultaid",
            name="hlab5801",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="labs.hlab5801",
            ),
        ),
        migrations.AddField(
            model_name="historicalultaid",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="ultaid",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("dateofbirth__isnull", True),
                        ("ethnicity__isnull", True),
                        ("gender__isnull", True),
                        ("hlab5801__isnull", True),
                        ("user__isnull", False),
                    ),
                    models.Q(("ethnicity__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="ultaids_ultaid_valid",
            ),
        ),
    ]
