# Generated by Django 4.2.6 on 2024-01-25 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ultaids", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalultaid",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ultaid",
            name="user",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="ultaid",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("dateofbirth__isnull", True),
                        ("ethnicity__isnull", True),
                        ("gender__isnull", True),
                        ("hlab5801__isnull", True),
                        ("user__isnull", False),
                    ),
                    models.Q(("ethnicity__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="ultaids_ultaid_valid",
            ),
        ),
    ]
