# Generated by Django 4.2.6 on 2024-01-28 20:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ultaids", "0003_historicalultaid_user_ultaid_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ultaid",
            name="medallergys",
        ),
        migrations.RemoveField(
            model_name="ultaid",
            name="medhistorys",
        ),
    ]
