# Generated by Django 4.2.6 on 2024-02-23 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ethnicitys", "0005_alter_ethnicity_value_and_more"),
        ("ultaids", "0004_remove_ultaid_medallergys_remove_ultaid_medhistorys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ultaid",
            name="ethnicity",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="ethnicitys.ethnicity"
            ),
        ),
    ]
