# Generated by Django 4.2.6 on 2023-11-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="blogpost",
            name="blog_blogpost_unique_slug",
        ),
        migrations.AddConstraint(
            model_name="blogpost",
            constraint=models.UniqueConstraint(fields=("title",), name="blog_blogpost_unique_title"),
        ),
    ]
