# Generated by Django 4.2.6 on 2024-07-29 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("flareaids", "0003_initial"),
        ("flares", "0002_initial"),
        ("akis", "0002_initial"),
        ("genders", "0001_initial"),
        ("dateofbirths", "0002_initial"),
        ("labs", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalflare",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalflare",
            name="urate",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Was a urate level measured during this flare?",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="labs.urate",
                verbose_name="Flare Urate",
            ),
        ),
        migrations.AddField(
            model_name="historicalflare",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="flare",
            name="aki",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="akis.aki"
            ),
        ),
        migrations.AddField(
            model_name="flare",
            name="dateofbirth",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="dateofbirths.dateofbirth"
            ),
        ),
        migrations.AddField(
            model_name="flare",
            name="flareaid",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="flareaids.flareaid"
            ),
        ),
        migrations.AddField(
            model_name="flare",
            name="gender",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="genders.gender"
            ),
        ),
        migrations.AddField(
            model_name="flare",
            name="urate",
            field=models.OneToOneField(
                blank=True,
                help_text="Was a urate level measured during this flare?",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="labs.urate",
                verbose_name="Flare Urate",
            ),
        ),
        migrations.AddField(
            model_name="flare",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="flare",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("dateofbirth__isnull", True),
                        ("flareaid__isnull", True),
                        ("gender__isnull", True),
                        ("user__isnull", False),
                    ),
                    models.Q(("dateofbirth__isnull", False), ("gender__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="flares_flare_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="flare",
            constraint=models.CheckConstraint(
                check=models.Q(("date_started__lte", django.db.models.functions.datetime.Now())),
                name="flares_flare_date_started_not_in_future",
            ),
        ),
        migrations.AddConstraint(
            model_name="flare",
            constraint=models.CheckConstraint(
                check=models.Q(("date_ended__gte", models.F("date_started"))), name="flares_flare_start_end_date_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="flare",
            constraint=models.CheckConstraint(
                check=models.Q(("likelihood__in", ["UNLIKELY", "EQUIVOCAL", "LIKELY"])),
                name="flares_flare_likelihood_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="flare",
            constraint=models.CheckConstraint(
                check=models.Q(("prevalence__in", ["LOW", "MEDIUM", "HIGH"])), name="flares_flare_prevalence_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="flare",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("joints__contains", "MTP1R"),
                    ("joints__contains", "MTP1L"),
                    ("joints__contains", "RFOOT"),
                    ("joints__contains", "LFOOT"),
                    ("joints__contains", "ANKLER"),
                    ("joints__contains", "ANKLEL"),
                    ("joints__contains", "KNEER"),
                    ("joints__contains", "KNEEL"),
                    ("joints__contains", "HIPR"),
                    ("joints__contains", "HIPL"),
                    ("joints__contains", "RHAND"),
                    ("joints__contains", "LHAND"),
                    ("joints__contains", "WRISTR"),
                    ("joints__contains", "WRISTL"),
                    ("joints__contains", "ELBOWR"),
                    ("joints__contains", "ELBOWL"),
                    ("joints__contains", "SHOULDERR"),
                    ("joints__contains", "SHOULDERL"),
                    _connector="OR",
                ),
                name="flares_flare_joints_valid",
            ),
        ),
    ]
