# Generated by Django 4.2.6 on 2023-11-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flares", "0003_remove_flare_flares_flare_diagnosed_valid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flare",
            name="date_ended",
            field=models.DateField(
                blank=True,
                default=None,
                help_text="What day did this flare resolve? Leave blank if it's ongoing.",
                null=True,
                verbose_name="Date Flare Resolved",
            ),
        ),
        migrations.AlterField(
            model_name="historicalflare",
            name="date_ended",
            field=models.DateField(
                blank=True,
                default=None,
                help_text="What day did this flare resolve? Leave blank if it's ongoing.",
                null=True,
                verbose_name="Date Flare Resolved",
            ),
        ),
    ]
