# Generated by Django 4.2.6 on 2024-08-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flares", "0003_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="flare",
            constraint=models.UniqueConstraint(
                condition=models.Q(("date_ended__isnull", True)),
                fields=("user", "date_ended"),
                name="flares_flare_one_active_flare_per_user",
            ),
        ),
    ]
