# Generated by Django 4.2.6 on 2024-01-10 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dateofbirths", "0004_alter_dateofbirth_value_and_more"),
        ("genders", "0005_alter_gender_value_alter_historicalgender_value"),
        ("flares", "0004_flare_user_historicalflare_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flare",
            name="dateofbirth",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="dateofbirths.dateofbirth"
            ),
        ),
        migrations.AlterField(
            model_name="flare",
            name="gender",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="genders.gender"
            ),
        ),
        migrations.AddConstraint(
            model_name="flare",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("dateofbirth__isnull", True), ("gender__isnull", True), ("user__isnull", False)),
                    models.Q(("dateofbirth__isnull", False), ("gender__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="flares_flare_valid",
            ),
        ),
    ]
