# Generated by Django 4.2.6 on 2024-08-23 11:09

from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flares", "0004_flare_flares_flare_one_active_flare_per_user"),
    ]

    operations = [BtreeGistExtension()]
