# Generated by Django 4.2.6 on 2024-08-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flares", "0006_flare_flares_flare_exclude_user_overlapping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flare",
            name="diagnosed",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "Provider wasn't sure"), (1, "Symptoms NOT from gout"), (2, "Symptoms from gout")],
                help_text="Did a medical provider think these symptoms were from gout?",
                null=True,
                verbose_name="Provider Diagnosis",
            ),
        ),
        migrations.AlterField(
            model_name="historicalflare",
            name="diagnosed",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "Provider wasn't sure"), (1, "Symptoms NOT from gout"), (2, "Symptoms from gout")],
                help_text="Did a medical provider think these symptoms were from gout?",
                null=True,
                verbose_name="Provider Diagnosis",
            ),
        ),
    ]
