# Generated by Django 4.2.6 on 2024-01-11 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("flares", "0006_alter_flare_dateofbirth_alter_flare_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flare",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
