# Generated by Django 4.2.6 on 2024-01-28 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("labs", "0007_historicalurate_remove_historicallab_history_user_and_more"),
        ("flares", "0007_alter_flare_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="HistoricalFlare",
            name="urate",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Was a urate level measured during this flare?",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="labs.urate",
                verbose_name="Flare Urate",
            ),
        ),
        migrations.AlterField(
            model_name="Flare",
            name="urate",
            field=models.OneToOneField(
                blank=True,
                help_text="Was a urate level measured during this flare?",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="labs.urate",
                verbose_name="Flare Urate",
            ),
        ),
        migrations.RemoveField(
            model_name="flare",
            name="medhistorys",
        ),
    ]
