# Generated by Django 5.1.3 on 2024-11-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flares", "0007_alter_flare_diagnosed_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalflare",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical flare",
                "verbose_name_plural": "historical flares",
            },
        ),
        migrations.AlterField(
            model_name="historicalflare",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
