# Generated by Django 4.2.6 on 2024-04-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flares", "0008_alter_historicalflare_urate_alter_flare_urate_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="flare",
            name="flares_flare_diagnosed_valid",
        ),
        migrations.AlterField(
            model_name="flare",
            name="diagnosed",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Symptoms due to gout"), (False, "Symptoms not from gout"), (None, "------")],
                help_text="Did a medical provider think these symptoms were from gout?",
                null=True,
                verbose_name="Provider Diagnosis",
            ),
        ),
        migrations.AlterField(
            model_name="historicalflare",
            name="diagnosed",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Symptoms due to gout"), (False, "Symptoms not from gout"), (None, "------")],
                help_text="Did a medical provider think these symptoms were from gout?",
                null=True,
                verbose_name="Provider Diagnosis",
            ),
        ),
        migrations.AddConstraint(
            model_name="flare",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("diagnosed__isnull", False),
                    models.Q(("crystal_analysis__isnull", True), ("diagnosed__isnull", True)),
                    _connector="OR",
                ),
                name="flares_flare_diagnosed_valid",
            ),
        ),
    ]
