# Generated by Django 4.2.6 on 2024-04-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flares", "0009_remove_flare_flares_flare_diagnosed_valid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flare",
            name="diagnosed",
            field=models.BooleanField(
                blank=True,
                choices=[
                    (True, "Symptoms due to gout"),
                    (False, "Symptoms not from gout"),
                    (None, "Provider was unsure"),
                    (None, "------"),
                ],
                help_text="Did a medical provider think these symptoms were from gout?",
                null=True,
                verbose_name="Provider Diagnosis",
            ),
        ),
        migrations.AlterField(
            model_name="historicalflare",
            name="diagnosed",
            field=models.BooleanField(
                blank=True,
                choices=[
                    (True, "Symptoms due to gout"),
                    (False, "Symptoms not from gout"),
                    (None, "Provider was unsure"),
                    (None, "------"),
                ],
                help_text="Did a medical provider think these symptoms were from gout?",
                null=True,
                verbose_name="Provider Diagnosis",
            ),
        ),
    ]
