# Generated by Django 4.2.6 on 2024-04-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flares", "0010_alter_flare_diagnosed_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="flare",
            name="flares_flare_diagnosed_valid",
        ),
        migrations.AlterField(
            model_name="flare",
            name="diagnosed",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Yes"), (False, "No")],
                help_text="Did a medical provider think these symptoms were from gout?",
                null=True,
                verbose_name="Provider Diagnosis",
            ),
        ),
        migrations.AlterField(
            model_name="historicalflare",
            name="diagnosed",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Yes"), (False, "No")],
                help_text="Did a medical provider think these symptoms were from gout?",
                null=True,
                verbose_name="Provider Diagnosis",
            ),
        ),
    ]
