# Generated by Django 4.2.6 on 2024-04-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flares", "0011_remove_flare_flares_flare_diagnosed_valid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flare",
            name="aki",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Yes"), (False, "No")],
                default=None,
                help_text="Did the patient have acute kidney injury during this flare?",
                null=True,
                verbose_name="Acute Kidney Injury",
            ),
        ),
        migrations.AddField(
            model_name="historicalflare",
            name="aki",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Yes"), (False, "No")],
                default=None,
                help_text="Did the patient have acute kidney injury during this flare?",
                null=True,
                verbose_name="Acute Kidney Injury",
            ),
        ),
    ]
