# Generated by Django 4.2.6 on 2024-05-12 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("akis", "0001_initial"),
        ("flares", "0015_remove_flare_aki_remove_historicalflare_aki"),
    ]

    operations = [
        migrations.AddField(
            model_name="flare",
            name="aki",
            field=models.OneToOneField(
                blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to="akis.aki"
            ),
        ),
        migrations.AddField(
            model_name="historicalflare",
            name="aki",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="akis.aki",
            ),
        ),
    ]
