# Generated by Django 4.2.6 on 2024-05-15 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("akis", "0002_alter_aki_ckd"),
        ("flares", "0016_flare_aki_historicalflare_aki"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flare",
            name="aki",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="akis.aki"
            ),
        ),
        migrations.AlterField(
            model_name="historicalflare",
            name="aki",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="akis.aki",
            ),
        ),
    ]
