from datetime import timedelta
from decimal import Decimal

from .choices import Freqs, Treatments, TrtTypes

# Dictionary of defaults for all ULT, Flare, and PPx Treatments for GoutHelper
TREATMENTS_DEFAULT_DOSING = {
    Treatments.ALLOPURINOL: {
        TrtTypes.ULT: {
            "dose": Decimal(100),
            "dose2": None,
            "dose3": None,
            "freq": Freqs.QDAY,
            "freq2": None,
            "freq3": None,
            "duration": None,
            "duration2": None,
            "duration3": None,
            "max_dose": Decimal(750),
            "dose_adj": Decimal(100),
        }
    },
    Treatments.CELECOXIB: {
        TrtTypes.FLARE: {
            "dose": Decimal(200),
            "dose2": Decimal(400),
            "dose3": None,
            "freq": Freqs.BID,
            "freq2": Freqs.ONCE,
            "freq3": None,
            "duration": timedelta(days=7),
            "duration2": None,
            "duration3": None,
            "max_dose": Decimal(400),
            "dose_adj": Decimal(200),
        },
        TrtTypes.PPX: {
            "dose": Decimal(200),
            "dose2": None,
            "dose3": None,
            "freq": Freqs.BID,
            "freq2": None,
            "freq3": None,
            "duration": None,
            "duration2": None,
            "duration3": None,
            "max_dose": Decimal(400),
            "dose_adj": Decimal(200),
        },
    },
    Treatments.COLCHICINE: {
        TrtTypes.FLARE: {
            "dose": Decimal("0.6"),
            "dose2": Decimal("1.2"),
            "dose3": Decimal("0.6"),
            "freq": Freqs.BID,
            "freq2": Freqs.ONCE,
            "freq3": Freqs.ONCE,
            "duration": timedelta(days=7),
            "duration2": None,
            "duration3": None,
            "max_dose": Decimal("1.2"),
            "dose_adj": Decimal("0.3"),
        },
        TrtTypes.PPX: {
            "dose": Decimal("0.6"),
            "dose2": None,
            "dose3": None,
            "freq": Freqs.QDAY,
            "freq2": None,
            "freq3": None,
            "duration": None,
            "duration2": None,
            "duration3": None,
            "max_dose": Decimal("0.6"),
            "dose_adj": Decimal("0.3"),
        },
    },
    Treatments.DICLOFENAC: {
        TrtTypes.FLARE: {
            "dose": Decimal(75),
            "dose2": None,
            "dose3": None,
            "freq": Freqs.BID,
            "freq2": None,
            "freq3": None,
            "duration": timedelta(days=7),
            "duration2": None,
            "duration3": None,
            "max_dose": Decimal(150),
            "dose_adj": Decimal(50),
        },
        TrtTypes.PPX: {
            "dose": Decimal(25),
            "dose2": None,
            "dose3": None,
            "freq": Freqs.BID,
            "freq2": None,
            "freq3": None,
            "duration": None,
            "duration2": None,
            "duration3": None,
            "max_dose": Decimal(150),
            "dose_adj": Decimal(50),
        },
    },
    Treatments.FEBUXOSTAT: {
        TrtTypes.ULT: {
            "dose": Decimal(40),
            "dose2": None,
            "dose3": None,
            "freq": Freqs.QDAY,
            "freq2": None,
            "freq3": None,
            "duration": None,
            "duration2": None,
            "duration3": None,
            "max_dose": Decimal(80),
            "dose_adj": Decimal(40),
        }
    },
    Treatments.IBUPROFEN: {
        TrtTypes.FLARE: {
            "dose": Decimal(800),
            "dose2": None,
            "dose3": None,
            "freq": Freqs.TID,
            "freq2": None,
            "freq3": None,
            "duration": timedelta(days=7),
            "duration2": None,
            "duration3": None,
            "max_dose": Decimal(800),
            "dose_adj": Decimal(200),
        },
        TrtTypes.PPX: {
            "dose": Decimal(400),
            "dose2": None,
            "dose3": None,
            "freq": Freqs.TID,
            "freq2": None,
            "freq3": None,
            "duration": None,
            "duration2": None,
            "duration3": None,
            "max_dose": Decimal(800),
            "dose_adj": Decimal(200),
        },
    },
    Treatments.INDOMETHACIN: {
        TrtTypes.FLARE: {
            "dose": Decimal(50),
            "dose2": None,
            "dose3": None,
            "freq": Freqs.TID,
            "freq2": None,
            "freq3": None,
            "duration": timedelta(days=7),
            "duration2": None,
            "duration3": None,
            "max_dose": Decimal(50),
            "dose_adj": Decimal(25),
        },
        TrtTypes.PPX: {
            "dose": Decimal(25),
            "dose2": None,
            "dose3": None,
            "freq": Freqs.BID,
            "freq2": None,
            "freq3": None,
            "duration": None,
            "duration2": None,
            "duration3": None,
            "max_dose": Decimal(50),
            "dose_adj": Decimal(25),
        },
    },
    Treatments.MELOXICAM: {
        TrtTypes.FLARE: {
            "dose": Decimal("15"),
            "dose2": None,
            "dose3": None,
            "freq": Freqs.QDAY,
            "freq2": None,
            "freq3": None,
            "duration": timedelta(days=7),
            "duration2": None,
            "duration3": None,
            "max_dose": Decimal("15"),
            "dose_adj": Decimal("7.5"),
        },
        TrtTypes.PPX: {
            "dose": Decimal("7.5"),
            "dose2": None,
            "dose3": None,
            "freq": Freqs.QDAY,
            "freq2": None,
            "freq3": None,
            "duration": None,
            "duration2": None,
            "duration3": None,
            "max_dose": Decimal("15"),
            "dose_adj": Decimal("7.5"),
        },
    },
    Treatments.METHYLPREDNISOLONE: {
        TrtTypes.FLARE: {
            "dose": Decimal(32),
            "dose2": Decimal(16),
            "dose3": None,
            "freq": Freqs.QDAY,
            "freq2": Freqs.QDAY,
            "freq3": None,
            "duration": timedelta(days=4),
            "duration2": timedelta(days=4),
            "duration3": None,
            "max_dose": Decimal(80),
            "dose_adj": Decimal(8),
        },
        TrtTypes.PPX: {
            "dose": Decimal(4),
            "dose2": None,
            "dose3": None,
            "freq": Freqs.QDAY,
            "freq2": None,
            "freq3": None,
            "duration": None,
            "duration2": None,
            "duration3": None,
            "max_dose": Decimal(80),
            "dose_adj": Decimal(8),
        },
    },
    Treatments.NAPROXEN: {
        TrtTypes.FLARE: {
            "dose": Decimal("440"),
            "dose2": None,
            "dose3": None,
            "freq": Freqs.BID,
            "freq2": None,
            "freq3": None,
            "duration": timedelta(days=7),
            "duration2": None,
            "duration3": None,
            "max_dose": Decimal("500"),
            "dose_adj": Decimal("220"),
        },
        TrtTypes.PPX: {
            "dose": Decimal("220"),
            "dose2": None,
            "dose3": None,
            "freq": Freqs.BID,
            "freq2": None,
            "freq3": None,
            "duration": None,
            "duration2": None,
            "duration3": None,
            "max_dose": Decimal("500"),
            "dose_adj": Decimal("220"),
        },
    },
    Treatments.PREDNISONE: {
        TrtTypes.FLARE: {
            "dose": Decimal("40"),
            "dose2": Decimal("20"),
            "dose3": None,
            "freq": Freqs.QDAY,
            "freq2": Freqs.QDAY,
            "freq3": None,
            "duration": timedelta(days=4),
            "duration2": timedelta(days=4),
            "duration3": None,
            "max_dose": Decimal("80"),
            "dose_adj": Decimal("20"),
        },
        TrtTypes.PPX: {
            "dose": Decimal("5"),
            "dose2": None,
            "dose3": None,
            "freq": Freqs.QDAY,
            "freq2": None,
            "freq3": None,
            "duration": None,
            "duration2": None,
            "duration3": None,
            "max_dose": Decimal("10"),
            "dose_adj": Decimal("2.5"),
        },
    },
    Treatments.PROBENECID: {
        TrtTypes.ULT: {
            "dose": Decimal(250),
            "dose2": None,
            "dose3": None,
            "freq": Freqs.BID,
            "freq2": None,
            "freq3": None,
            "duration": None,
            "duration2": None,
            "duration3": None,
            "max_dose": Decimal(1000),
            "dose_adj": Decimal(250),
        }
    },
}


def treatments_get_default_dosing():
    return TREATMENTS_DEFAULT_DOSING
