# Generated by Django 4.2.6 on 2024-07-29 15:15

from django.db import migrations, models
import django_extensions.db.fields
import gouthelper.utils.models
import rules.contrib.models
import simple_history.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aki",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ongoing", "Ongoing"), ("improving", "Improving"), ("resolved", "Resolved")],
                        default="ongoing",
                        help_text="The status of this AKI.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
            ],
            bases=(rules.contrib.models.RulesModelMixin, gouthelper.utils.models.GoutHelperBaseModel, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAki",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("ongoing", "Ongoing"), ("improving", "Improving"), ("resolved", "Resolved")],
                        default="ongoing",
                        help_text="The status of this AKI.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
            ],
            options={
                "verbose_name": "historical aki",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
