# Generated by Django 4.2.6 on 2024-05-15 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("medhistorys", "0012_delete_allopurinolhypersensitivity_and_more"),
        ("akis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aki",
            name="ckd",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="akis",
                to="medhistorys.ckd",
                verbose_name="CKD",
            ),
        ),
    ]
