# Generated by Django 4.2.6 on 2024-07-29 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("akis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalaki",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalaki",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aki",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="aki",
            constraint=models.CheckConstraint(
                check=models.Q(("user__isnull", False), ("user__isnull", True), _connector="OR"),
                name="akis_aki_user_ppx_exclusive",
            ),
        ),
        migrations.AddConstraint(
            model_name="aki",
            constraint=models.CheckConstraint(
                check=models.Q(("status__in", ["ongoing", "improving", "resolved"])), name="akis_aki_status_is_valid"
            ),
        ),
    ]
