# Generated by Django 4.2.6 on 2024-10-10 11:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("akis", "0002_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="aki",
            name="akis_aki_user_ppx_exclusive",
        ),
    ]
