# Generated by Django 4.2.6 on 2024-05-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("akis", "0002_alter_aki_ckd"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="aki",
            name="akis_aki_user_ppx_exclusive",
        ),
        migrations.RemoveField(
            model_name="aki",
            name="ckd",
        ),
        migrations.RemoveField(
            model_name="aki",
            name="dateofbirth",
        ),
        migrations.RemoveField(
            model_name="aki",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="historicalaki",
            name="ckd",
        ),
        migrations.RemoveField(
            model_name="historicalaki",
            name="dateofbirth",
        ),
        migrations.RemoveField(
            model_name="historicalaki",
            name="gender",
        ),
        migrations.AddConstraint(
            model_name="aki",
            constraint=models.CheckConstraint(
                check=models.Q(("user__isnull", False), ("user__isnull", True), _connector="OR"),
                name="akis_aki_user_ppx_exclusive",
            ),
        ),
    ]
