# Generated by Django 4.2.6 on 2024-05-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("akis", "0003_remove_aki_akis_aki_user_ppx_exclusive_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aki",
            name="resolved",
            field=models.BooleanField(
                default=False,
                help_text="Has this AKI resolved? (i.e., has the creatinine level returned to normal?)",
                verbose_name="Resolved",
            ),
        ),
        migrations.AddField(
            model_name="historicalaki",
            name="resolved",
            field=models.BooleanField(
                default=False,
                help_text="Has this AKI resolved? (i.e., has the creatinine level returned to normal?)",
                verbose_name="Resolved",
            ),
        ),
    ]
