# Generated by Django 4.2.6 on 2024-05-19 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("akis", "0004_aki_resolved_historicalaki_resolved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aki",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
