# Generated by Django 4.2.6 on 2024-06-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("akis", "0005_alter_aki_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aki",
            name="resolved",
        ),
        migrations.RemoveField(
            model_name="historicalaki",
            name="resolved",
        ),
        migrations.AddField(
            model_name="aki",
            name="status",
            field=models.CharField(
                choices=[("ongoing", "Ongoing"), ("improving", "Improving"), ("resolved", "Resolved")],
                default="ongoing",
                help_text="The status of this AKI.",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="historicalaki",
            name="status",
            field=models.CharField(
                choices=[("ongoing", "Ongoing"), ("improving", "Improving"), ("resolved", "Resolved")],
                default="ongoing",
                help_text="The status of this AKI.",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
