# Generated by Django 4.2.6 on 2024-06-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("akis", "0006_remove_aki_resolved_remove_historicalaki_resolved_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="aki",
            constraint=models.CheckConstraint(
                check=models.Q(("status__in", ["ongoing", "improving", "resolved"])), name="akis_aki_status_is_valid"
            ),
        ),
    ]
