# Generated by Django 4.2.6 on 2023-11-04 22:06

from django.db import migrations  # type: ignore

from ..services import create_or_update_contents


class Migration(migrations.Migration):
    dependencies = [
        ("contents", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_or_update_contents)]
