# Generated by Django 4.2.6 on 2023-12-21 21:00

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_managers_alter_historicaluser_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="created"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
        ),
        migrations.AddField(
            model_name="user",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="created"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
        ),
    ]
