# Generated by Django 4.2.6 on 2023-12-22 20:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_historicaluser_created_historicaluser_modified_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalUser",
        ),
    ]
