# Generated by Django 4.2.6 on 2023-12-22 20:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_historicaluser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaluser",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="user",
            name="creator",
        ),
    ]
