# Generated by Django 4.2.6 on 2023-12-22 21:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_remove_historicaluser_creator_remove_user_creator"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalUser",
        ),
    ]
