# Generated by Django 4.2.6 on 2024-01-09 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_historicaluser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="admin",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="patient",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="provider",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="pseudopatient",
            options={"get_latest_by": "modified"},
        ),
    ]
