# Generated by Django 4.2.6 on 2024-02-21 22:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_admin_options_alter_patient_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Pseudopatient",
        ),
    ]
