# Generated by Django 4.2.6 on 2024-02-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_delete_pseudopatient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluser",
            name="role",
            field=models.CharField(
                choices=[
                    ("PATIENT", "Patient"),
                    ("PROVIDER", "Provider"),
                    ("PSEUDOPATIENT", "Pseudopatient"),
                    ("ADMIN", "Admin"),
                ],
                default=None,
                max_length=50,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("PATIENT", "Patient"),
                    ("PROVIDER", "Provider"),
                    ("PSEUDOPATIENT", "Pseudopatient"),
                    ("ADMIN", "Admin"),
                ],
                default=None,
                max_length=50,
                verbose_name="Role",
            ),
        ),
    ]
