# Generated by Django 4.2.6 on 2024-02-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_historicaluser_role_alter_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pseudopatient",
            fields=[],
            options={
                "get_latest_by": "modified",
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.user", models.Model),
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="role",
            field=models.CharField(
                choices=[
                    ("PATIENT", "Patient"),
                    ("PROVIDER", "Provider"),
                    ("PSEUDOPATIENT", "Pseudopatient"),
                    ("ADMIN", "Admin"),
                ],
                default="PROVIDER",
                max_length=50,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("PATIENT", "Patient"),
                    ("PROVIDER", "Provider"),
                    ("PSEUDOPATIENT", "Pseudopatient"),
                    ("ADMIN", "Admin"),
                ],
                default="PROVIDER",
                max_length=50,
                verbose_name="Role",
            ),
        ),
    ]
